### ISSUE TITLE
iFunEngine 매치메이킹 시스템 Group vs Group 기능 문의

### ISSUE THREAD

**Issue by dkmoon** [iFunEngine/iFunEngine#167]
안녕하세요 현재 c#으로 Group vs Group 매칭 시스템을 구현 중에 있는데 혹시 c# Group vs Group 예제 코드 업데이트 일정 알 수 있을까요? 아니면 따로 구현되어있는 예제 코드를 받을 수 있을지 문의 드립니다.

**Comment by dkmoon** [comment]
안녕하세요. 아이펀팩토리입니다. 매뉴얼의 매치메이킹 예제의 C# 버전은 C++ 버전과 비교했을 때, 언어의 특징적인 부분 외에 인터페이스에는 큰 차이가 없어서 아직 준비하고 있지 않은 상태입니다. 가까운 시일 안에 준비해서 게시할 수 있도록 하겠습니다. 불편을 드려 죄송합니다.

**Comment by dkmoon** [comment]
네 잘부탁드리겠습니다. 감사합니다!

**Comment by jwlee-ifun** [comment]
이 후 C# 예제가 추가되고 최신 버전의 아이펀 엔진에 맞게 튜토리얼이 수정되었습니다.
