### ISSUE TITLE
매치메이킹시 플레이중인 매치에 참여하는 방법?

### ISSUE THREAD

**Issue by dkmoon** [iFunEngine/iFunEngine#229]
_2020년 5월 14일 newtrocode 님이 올리신 질문입니다._

안녕하세요.

현재 매치메이킹을 통해 데디케이트를 실행하고 진입하는 것까지 진행한 상태입니다.

목적은 기존에 플레이중인 게임들 중 인원이 부족한 데디를 찾아서 신규 유져를 참여시키고자 합니다.

테스트로 `funapi.Matchmaking.Client.Start` 에서 match callback 에서

`DedicatedServerManager.SendUsers` 를 호출하니 정상적으로 동작 합니다.

그런데 매치메이킹 timeout 이 뜰때까지 콜백이 들어오지 않는데 다른 방법은 없는가요?

좋은 방법이 있다면 가이드 부탁드립니다.

두번째로 플레이중인 매칭 정보를 `funapi.Matchmaking.Client.GetMatchmakingServerInfo` 를 통해서 받으면

서버가 여러대일 경우에도 전역 매칭 정보를 얻을 수 있는거가요?

**Comment by jwlee-ifun** [comment]
안녕하세요. 아이펀팩토리입니다.

먼저 첫번째 질문에 대해서 두가지 구현 방법을 생각해 볼 수 있겠습니다.

첫번째는 현재 플레이중이지만 인원이 부족한 DediServer 를 Matchmaking 에 넣어두고 match callback 을 통해서 유저를 보내는 방식인데요, 이 경우는 match callback 대신 progress callback 을 사용하면 match callback 이 불리기 전 중간중간에 User 를 참여시킬 수 있을 것으로 생각합니다.

사용하기 위해서는 아래의 `enable_match_progress_callback` 을 `true` 로 설정해 주시기 바랍니다.

    "MatchmakingServer": {
      // dynamic match 는 이미 매칭 풀에 있는 매치들끼리도 매칭을 시도해서
      // 매칭 풀이 적은 상황에서 주건을 완화시키면서 다시 매칭을 돌릴 때 유효합니다.
      "enable_dynamic_match": true,
      "enable_match_progress_callback": false,
      "concurrent_number_of_players_threshold": 3000
    },

단, 이 경우에는 DediServer 에 해당하는 Match 를 유지해야 하기 때문에 `enable_dynamic_match` 옵션은 사용하시면 안됩니다.

두번째 방법은 DediServer 의 부족한 인원만큼의 Match (1명을 기다리는) 를 만들어서 각 Match 가 성사되면 DediServer 로 보내주는 방법이 있겠습니다. 이 방법은 dynamic 매칭을 사용할 수 있는 장점이 있지만 비어있는 인원 수 만큼의 Match 를 관리 해 줘야 합니다.

그리고, 마지막에 질문 해 주신 내용은 Match 서버가 여러대에 나눠져 있고 모두 하나의 RPC 그룹으로 묶여있다면 `GetMatchmakingServerInfo` 함수로 MatchmakingServer 정보를 받았을 때, 전역 매칭 정보를 바탕으로 특정 플레이 중인 매칭 정보를 찾을 수 있습니다.
