### ISSUE TITLE
max_servers_for_ds_host 에 도달 했을 때 이벤트 콜백 

### ISSUE THREAD

**Issue by newtrocode** [iFunEngine/iFunEngine#233]
안녕하세요. 

가용자원이 부족한 상황을 연출해서 테스트를 진행 했습니다.

max_servers_for_ds_host를 1로 두고 2번째 데디케이트 서버 스폰 요청시 다음과 같은 로그가 출력 됩니다.

```
E0527 03:58:16.700242 22739 dedicated_server_manager.cc:2977] Failed to select a HostManager: result code=2, message=Not enough capacity, match request={"peer_id":"02068ca7-3400-4f1f-0000-000000000000","match_id":"8b5ba879-2300-0000-b69e-73fedbdca3af"}
W0527 03:58:16.700474 22739 dedicated_server_manager.cc:3043] Failed to select a HostManager. No available HostManager to handle this match: request={"peer_id":"02068ca7-3400-4f1f-0000-000000000000","match_id":"8b5ba879-2300-0000-b69e-73fedbdca3af"}
I0527 03:58:16.700492 22739 dedicated_server_manager.cc:3076] There's no available server, retry after few seconds: seconds=3
```

이 부분에 대해 콜백을 받고 싶습니다.

추가적으로 현재 스폰된 데디케이트 수(진행중인 매치 수)를 구할 때는 

redis에 ife-dedi-matches 카운트 하면 될 것 같은데

해당 키를 게임서버에서 접근해서 사용해도 무방한가요?

**Comment by newtrocode** [comment]
추가적으로 말씀드리면, 

매칭이 성공하고 데디케이트 스폰 요청 후에 

데디케이트가 스폰이 되지 않았을 때의 상황을

핸들링 하고 싶습니다.

**Comment by jwlee-ifun** [comment]
안녕하세요. 아이펀 팩토리입니다.

먼저, `Not enough capacity` 에 대한 콜백을 요청 해 주셨는데요, Spawn 요청은 match_id 중복처럼 요청 파라미터가 잘 못된 경우를 제외하면, 데디케이티스 서버의 상태가 조금씩 변하면서 `Not enough capacity` 상태같은 경우는 해소될 수가 있기 때문에 Spawn 을 다시 시도하게 됩니다.

Timeout 으로 정해진 시간만큼 재시도를 해도 실패하는 경우에 종합적으로 Spawn 실패를 전달하게 됩니다.

`Not enough capacity` 콜백에서 하려는 동작이 무엇인지 알려주실 수 있으실까요?

두번째로 질문해 주신 현재 스폰된 데디케이티드 수를 구하는 방법에 대해서는 기본적으로 게임 서버가 Redis Key 를 읽는 것은 문제가 되지 않습니다. `ife-dedi-hosts` 키와 `ife-dedi-matches` 키를 참고하시기 바랍니다.

또는 엔진의 ApiService 기능을 사용하신다면 `/v1/dedicated_server/servers/` URI 를 호출해서 말씀하신 정보를 얻을 수도 있습니다.

**Comment by newtrocode** [comment]
답변 감사합니다.

not enough capacity 과 관련된 콜백을 요청드린 이유는 두가지 입니다.

첫번째로 데디케이트 서버를 AWS 오토스케일 적용시 CPU나 memory 부하로는 

실제 스케일아웃을 해야 하는 시점을 파악하기 힘들것 같습니다.

그래서 capacity가 부족한 경우에 aws-cli로 데디케이트 관련(데디케이트 호스트 메니져와 데디케이트 서버) 인스턴스를 늘려 주는 시나리오를 구상하고 있었습니다.


두번쨰는 매칭이 실패하는 장애 상황에 대한 판단을 위해 로깅용으로 콜백을 사용하려고 합니다.

**Comment by jwlee-ifun** [comment]
두번째로 언급해 주신 `매칭` 역시 spawn 요청을 의미하시나요?

**Comment by newtrocode** [comment]
네 맞습니다.

**Comment by jwlee-ifun** [comment]
확인 감사합니다.

우선, 데디케이티스 서버를 AWS 에서 사용하시는 경우 엔진 수준에서 EC2 인스턴스의 오토스케일을 지원하는 기능이 이미 엔진에 있는데요, region 을 지정하고 min, max, reserved_instances 설정에 맞게 EC2 호스트를 늘려주고 줄여주도록 동작합니다.

관련 내용을 수일내로 정리해서 매뉴얼을 통해서 안내해 드리도록 하겠습니다.

확인해 보시고 만약, 기대하시는 동작과 다른 부분이 있다면 의견 주시면 감사하겠습니다.

**Comment by newtrocode** [comment]
DedicatedServerManager.RegisterConfigureReservedInstanceCountCallback() 부분을 등록해놨는데 

콜백이 안들어와서 미구현 API 인가 했는데 이미 기능이 있었군요 ^^;

추후 메뉴얼 확인 후에 관련 부분 진행해 보도록 하겠습니다.

답변 감사드립니다.

**Comment by jwlee-ifun** [comment]
아이펀 엔진 매뉴얼에 AWS 상에서 데디케이티드 서버를 호스팅하는 방법을 설명하는 내용이 추가되었습니다. ([링크](https://www.ifunfactory.com/engine/documents/reference/ko/dedicated-server-aws.html))

감사합니다.
