### ISSUE TITLE
서버위치와 데이터베이스 코드 순차실행

### ISSUE THREAD

**Issue by coldstartist** [iFunEngine/iFunEngine#235]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_:  18.04
* 개발 언어 _(C++/C#)_: C++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: VS Code
* 아이펀 엔진 버전: ...
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unity
* 클라이언트 플러그인 버전: ...

안녕하세요. 초보개발자입니다.

현재 런던에서 개발중입니다. 서버는 런던 ec2 인스턴스에 올려두었습니다.
다름이 아니고 게임 개발이 끝나고 서버를 실행시키고 난 뒤 제가 있는 영국에서는 에러가 안납니다. 그런데 한국에 있는 플레이어는 연결이 계속 끊긴다고 합니다. 

이런경우가 있었었는지는 모르겠지만 간략하게 요점은

- 게임설치후 실행시 문제없이 서버와 교신 잘됨.
- 모바일에서 실행중인 게임창을 위로 올려서 게임 종료후 재접속시 세션 생성이 안됨. 

반대로 새로운 인스턴스를 서울에 만들어놓고 서버를 패키지화한후 풀어보니 이제는 런던의 제 휴대폰에서 오작동합니다. 
이것은 서버가 너무멀다보니 생기는 이슈일까요? 

```c#
private void Awake()
    { 
        OnAwakeConnect();
    }
    public void OnAwakeConnect ()
    {
        if (session == null || address_changed)
        {
            createSession();
        }
        TransportOption option = null;
        TcpTransportOption tcp = new TcpTransportOption();
        tcp.AutoReconnect = false;
        option = tcp;
        session.Connect(TransportProtocol.kTcp, FunEncoding.kJson, 8012, option);
    }

void Start()
    {
        if (platform == null)
     {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();

        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.DebugLogEnabled = true;
        platform = PlayGamesPlatform.Activate();
        }
    Social.localUser.Authenticate(success => {
        if (success){
            PlayerID = Social.localUser.id;
            StartCoroutine(GetUserData());
        }
        else {
        }
    });
    }
     IEnumerator GetUserData()
     {
        yield return new WaitForSeconds(0.3f);
        UserLogIn();
        GetChallengeCount();
        GetHighestScore();
        GetItemData();
    }
```

관련이 있지만 별개로
코드를 보시면 GetUserData함수가 0.3초뒤에 실행이 됩니다.
전에 여쭤보려고 했었는데 0.3초를 넣지않으면         
GetChallengeCount();
GetHighestScore();
 GetItemData();
세션이 생기기전에 저함수들이 실행되어 함수들이 스킵되어버립니다. 코루틴써서 0.3초로 하는게 상당히 애매해서  콜백형식으로 반드시 세션이 생기고 나서 저 함수들이 실행되게 하고 싶습니다. 어떻게 하는게 가장 효율적인 방법일까요? 

핑이 높아서 저 함수들이 실행이 안되는것일까요? 디버그 로그를 보면 Failed to log in도 안뜨는것으로 보아 서버가 실행이 안되는거 같은데 이유를 알수가 없습니다.

마지막으로 데이터베이스에 관한 질문입니다. 

"Object": {
            "enable_database" : true,
........
            "db_mysql_server_address" : "tcp://127.0.0.1:3306",

데이터베이스를 런던의 인스턴스에 있는것으로 쓰고 싶다고 하면 ip를 바꿔줘야하는데 액세스 거부가 나옵니다.
퍼블릭 키를 사용하여 연결시킬려면 어떻게 하는게 좋습니까?

긴 질문 읽어주셔서 감사합니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

순서대로 답변을 드리도록 하겠습니다.

첫째, 

> 서울에 위치한 클라이언트가 영국의 서버에 접속하더라도 게임 설치 직후 실행시에는 문제없이 서버와 연결이 잘 되는건가요?
> 
> 접속이 되지 않을 때의, 서버 쪽 INFO 로그를 짤라서 함께 올려주시면 원인을 파악하는데 도움이 될 것 같습니다.
> 

둘째,

> Session 이 생성됐을 때, 콜백을 받아서 통신이 시작되게 구성하는 방법은 Session 의 EventCallback 을 등록해서 kConnected 이벤트를 확인하는 방법을 사용하시면 됩니다.
> 
> Unity 플러그인 프로젝트나 Pong 게임 프로젝트를 통해서 서버와 연결하고, 재연결하는 방법에 대한 샘플을 제공하고 있으나, 한번 확인해 보시면 도움이 되실 것 같습니다.
> 

마지막으로 DB 에 접속할 때 발생하는 오류는

1. 게임 서버가 AWS 런던 리전 밖에 있다면 가장 먼저 DB 가 실행되는 호스트의 3306 포트가 외부(Public Network) 에 열려있어야 합니다. AWS 의 보안 그룹 설정을 참고하시기 바랍니다. 

2. "db_mysql_id" 에 해당하는 MySQL 사용자의 로케이션이 localhost 로 되어 있는 것 같습니다.
예를들어, 로컬 호스트와 리모트 호스트에서 모두 사용할 "my_account" 라는 계정을 생성하기 위해서는 다음과 같이 두 개의 계정을 생성해야 합니다.
```
mysql) CREATE USER "my_account"@localhost IDENTIFIED BY "my_passwd"; << 같은 호스트에서만 접속할 수 있는 "my_account" 를 생성.
mysql) CREATE USER "my_account"@'%' IDENTIFIED BY "my_passwd"; << 모든 리모트 호스트에서 접속할 수 있는 "my_account" 를 생성.
```
마찬가지로 권한을 설정하는 GRANT 명령 역시 두 개의 계정 각각에 대해서 실행해 줘야합니다.

보내주신 내용으로 짐작했을 때는 2번이 문제일 가능이 높아 보입니다만, 마찬가지로 로그 내용을 보내주시면 정확한 내용을 파악하는데 도움이 될 것 같습니다.

감사합니다.
