### ISSUE TITLE
[질문]UDP 사용 문의 드립니다

### ISSUE THREAD

**Issue by mkmk8846** [iFunEngine/iFunEngine#236]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_:  CentOS 7
* 개발 언어 _(C++/C#)_:C++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_:  VS
* 아이펀 엔진 버전: ...
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unity
* 클라이언트 플러그인 버전: ...

**어떤 점이 궁금하신가요?**
안녕하세요 현재 아이펀 엔진 인디 라이센스로 PVP게임을 개발 하고있습니다.
실시간 PVP게임을 만들면서 TCP가 아닌 UDP로 메시지를 주고 받으려 하고 있는데요
아이펀 엔진 자체에서 reliable udp 지정할 수 있는 옵션이 있는지요 
아니면 reliable udp 메시지를 새로 구현 해야하는지요?

**Comment by jwlee-ifun** [comment]
안녕하세요.

안타깝게도 Reliable UDP 기능은 아이펀 엔진에서 따로 제공하지 않고 있습니다.

TCP 와 UDP 프로토콜을 함께 사용하는 것은 어떠실지요.

**Comment by mkmk8846** [comment]
> 안녕하세요.
> 
> 안타깝게도 Reliable UDP 기능은 아이펀 엔진에서 따로 제공하지 않고 있습니다.
> 
> TCP 와 UDP 프로토콜을 함께 사용하는 것은 어떠실지요.

TCP와 UDP 혼합으로 사용 하는 방향으로 가야겠네요
빨른 답변 감사합니다 ^^
