### ISSUE TITLE
서버 사용량 한계치

### ISSUE THREAD

**Issue by coldstartist** [iFunEngine/iFunEngine#237]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: 우분투 bionic
* 개발 언어 _(C++/C#)_: ... c++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: ...VS code
* 아이펀 엔진 버전: ...
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: ...
* 클라이언트 플러그인 버전: ...

언제나 감사드립니다.

게임 출시를 앞두고 테스트 중입니다. 다름이 아니라 아마존 인스턴스를 2코어 램 4GB로 사용중인데 유저가 얼마나 사용해야 서버가 제대로 작동하지 않는 상황이 올까 궁금합니다.

제가 사용중인 서버 교신용 코드는, 아이템 데이터를 게임 시작시마다 받아오는것 (짧은 룸베이스기반), 세션이 열리면 플레이어 정보를 받아오는것, 아이템 사용시 서버에 기록, 아이템 구매시 서버에 기록등 짧고 간결한 코드들인데 지금은 5~6명정도가 테스트중이라 문제가 없는것 같지만 유저수가 늘어나면 서버가 터질까봐 걱정입니다.

그렇게 되기전에 게임리프트에 올려야 되나 생각도 들고 그래서 여쭤봅니다.

**Comment by jwlee-ifun** [comment]
안녕하세요. 아이펀팩토리입니다.

먼저, 개발이 잘 진행되어 출시를 앞두고 테스트를 진행하고 계신다니 축하드립니다!

질문해 주신 것처럼 출시 준비시 서버 운용 규모를 가늠하기 위해 최소 단위의 서버군이 수용가능한 클라이언트 수를 확인할 필요가 있는데요, 게임마다 구현 내용이 다르기 때문에 서버가 수용 가능한 클라이언트 수의 한계치도 달라질 것입니다.

따라서, 저희는 일반적으로 더미 클라이언트를 실행해서 얻은 테스트 데이터를 토대로 판단하는 것을 권장하고 있습니다.

먼저, 그 전에 현재 서버에 구현한 메시지 핸들러를 비롯한 각 이벤트 처리 로직의 실행시간이 적절한지 확인 볼 필요가 있습니다. 특히 호출 빈도가 높은 메시지 핸들러의 실행 시간이 길다면 이것은 전체 서버의 성능 저하와 직결되기 때문에 구현 내용을 다시 검토해 봐야 할 것입니다.

[이벤트 프로파일링 및 디버깅 매뉴얼](https://www.ifunfactory.com/engine/documents/reference/ko/event.html#event-debugging) 을 참고하셔서 각 이벤트들의 수행시간을 확인 해 보시기 바랍니다.

이렇게 서버의 성능을 최적화했다면 gamelift 의 AutoScale 설정을 적용해서 서버를 확장하거나 서버당 한계치를 가능한 정밀하게 측정해서 예상되는 동시 접속 클라이언트 수를 수용할 수 있도록 필요한 서버들을 준비할 수 있을 것입니다.

가능하시다면 [서버 테스트용 Bot 작성 매뉴얼](https://www.ifunfactory.com/engine/documents/reference/ko/bot.html) 의 예제 코드를 참고하셔서 더미 클라이언트를 작성하신 후 부하 테스트를 돌려 볼 것을 권해 드립니다.

여러 고객사의 경우를 봤을 때, 사전에 성능 테스트를 진행한 경우와 그렇지 않은 경우에 라이브 서비스에서 문제가 발생하는 빈도에서 차이가 있었습니다. 

테스트 과정에서 도움이 필요한 필요한 부분이 있으시다면 문의 남겨 주시기 바랍니다.

**Comment by coldstartist** [comment]
안녕하세요

답변 감사드립니다.

일단은 첨부해놓은 스크린샷을 보시면 execution_time_mean_in_sec 과 queue_time_mean_in_sec 값이
나노초 정도로 나오는것을 확인했습니다.
이경우에는 큐타임을 기준으로 몇만명까지는 1초내로 처리할수있다는것을 뜻하는것일까요?

그리고 말씀해주신 봇 작성 매뉴얼을 보았는데 조금 번거로워 보이는데 본질은 서버에 클라이언트가 5000번정도 교신을 한다정도인것같습니다.
그렇다면 테스트용을 따로 만들지 않고 원래쓰던 클라이언트 매니저에서 따로 실험을 해봐도 되지않을까요?

감사합니다.

**Comment by jinukkim** [comment]
예상되는 인원 수 기준의 bot 테스트는 꼭 해보시길 권장합니다.
한 명의 유저로 테스트해서 나온 시간이 많은 수의 유저 (100명, 1000명, ...) 가 접속했을 때와 동일하게 나오지 않는 경우가 대부분입니다.

많은 수의 bot을 붙였을 때 나오는 이벤트 프로파일링 결과로 아래와 같은 부분에 병목이 있을지 확인할 수 있습니다:

- 유저 간 상호 작용 (서로 메시지를 보내거나, 한 명이 보내서 여러 명이 받는 메시지가 많은 경우) 이 있는 경우, 이 상호 작용이 얼마나 느린지에 따라 성능이 달라집니다. 그리고 이건 인원 수에 비례 혹은 인원 수 제곱에 비례해서 느려질 수 있습니다. (게임 컨텐츠나 구현하는데 사용한 방법에 따라 다릅니다)
- DB 혹은 redis 성능: 한 두 명의 유저에서는 이 부분에 병목을 일으키는게 어렵습니다. 하지만 유저 수가 늘어난다면 설정한 DB 용량, redis 용량에 따라서 병목이 나타날 수 있고, 유저 수가 증가함에 따라 사용 방식에 따른 병목이 나타날 수 있습니다. 
- 이 외에도 예측하기 어려운 부분 (외부 제3자 서비스 연동) 에서 병목이 나올 수 있습니다.

**Comment by coldstartist** [comment]
답변 감사드립니다.

봇 테스트를 해봐야 하는것은 알고 있습니다. 다만 제가 여쭤보고싶은것은 테스트용을 따로만드는것이 아닌 기존의 메인 클라이언트매니저에서
봇을 만들어서 돌려도 괜찮겠습니까?

**Comment by jinukkim** [comment]
Unity 를 써서 테스트 봇을 돌리는 것은 권장하지 않습니다.
메모리 사용량이나 동시에 열 수 있는 소켓 수 제한 때문에 많은 수의 테스트 봇을 구동하기 어렵습니다.

[서버 테스트용 봇 작성](https://www.ifunfactory.com/engine/documents/reference/ko/bot.html) 쪽의 내용을 참고하시어 작성하시는게 좋습니다.

**Comment by coldstartist** [comment]
알겠습니다.

그런데 조금 헷갈리는 부분이 있습니다.

"게임 서버 코드에 이 콤포넌트를 포함시켜 별도의 서버 인스턴스로 띄우게 되면"

이 말은 서버코드안에 테스트용 코드를 집어넣어두고 서버가 시작되면 테스트봇이 예를 들어 3000번 호출을 한다는 말인가요?
외부에서는 전혀 건드리지 않고 서버안에서 서버를 호출하게 되는것인지 헷갈려서 질문드립니다.

tatic bool Start() {  funtest::Network::Install(OnSessionOpened,
OnSessionClosed, 4);
funtest::Network::RegisterTcpTransportHandler(OnTcpAttached,
OnTcpDetached);  funtest::Network::Register2("pbuf_echo", OnEcho);
  // Created 300 clients.
  for (size_t i = 0; i < 300; ++i) {    Ptr<funtest::Session> session
= funtest::Session::Create();    session->GetContext()["count"] =
5000;    session->ConnectTcp("127.0.0.1", 8013, kProtobufEncoding);  }

  return true;}

이 함수는 서버가 시작하면 저절로 실행되는 함수인가요?

전체적인 워크플로우가 머리속에 들어오지않습니다. 조금 알려주십시오.

감사합니다.

**Comment by jinukkim** [comment]
"게임 서버 코드에 이 컴퍼넌트를 포함"은 아래와 같은 내용입니다.

1. 게임 서버에 flavor 추가 (예를 들어 bot)
2. 게임 서버의 Start() 함수 내에서 bot 이 할 테스트에 해당하는 코드 추가. 이 Start 함수는 서버 내의 구성요소들이 초기화한 후 호출하는 함수입니다.

"별도의 서버 인스턴스로 띄우기"는 {프로젝트이름).bot-launcher 혹은 {프로젝트이름}.bot-local 로 서버 프로세스를 새로 띄운다는 의미입니다.

**Comment by coldstartist** [comment]
서버코드 이벤트핸들러.cc의 메인 네임스페이스 밑에 아래와 같이 써놨는데 에러가 뜨네요. 전혀 안내가 나와있지 않으니 그냥 막하는것
같습니다. 스텝을 좀 알려주실수 있으시겠습니까?

namespace funtest {

class Network {
public:
// session 이 열리고 닫힐 때 호출될 callback 과 io thread 의 수를
// 설정합니다. 이 함수는 반드시 가장먼저 호출해야 합니다.
static void Install(const SessionOpenedHandler &opened_handler,
const SessionClosedHandler &closed_handler,
size_t io_threads_size);

// 필요할 경우 TCP 연결이 맺어지고, 끊길 때 호출될 callback 을 지정합니다.
static void RegisterTcpTransportHandler(
const TcpTransportAttachedHandler &tcp_attached_handler,
const TcpTransportDetachedHandler &tcp_detached_handler);

// JSON 타입의 메시지 핸들러를 등록합니다.
static void Register(const string &message_type,
const MessageHandler &message_handler);

// Protobuf 타입의 메시지 핸들러를 등록합니다.
static void Register2(const string &message_type,
const MessageHandler2 &message_handler);
};
namespace funtest {

class Session {
public:
DECLARE_CLASS_PTR(Session);

enum State {
kOpening,
kOpened,
kClosed
};

// 세션 객체를 생성합니다. 이 함수를 호출한다고 세션이 맺어지는 것은
// 아닙니다. TCP 연결을 위해서는 아래 ConnectTcp(...) 함수를 이용해야됩니다.
static Ptr<Session> Create();

virtual ~Session();

// TCP 로 서버에 접속합니다. 만약 첫 연결이면 세션이 열리게 됩니다.
// 그렇지 않은 경우에는 이미 존재하던 세션을 계속 재사용하게 됩니다.
virtual void ConnectTcp(const string &ip, uint16_t port,
EncodingScheme encoding) = 0;
virtual void ConnectTcp(const boost::asio::ip::tcp::endpoint &endpoint,
EncodingScheme encoding) = 0;

// UDP 로 서버에 접속합니다. 만약 첫 연결이면 세션이 열리게 됩니다.
// 그렇지 않은 경우에는 이미 존재하던 세션을 계속 재사용하게 됩니다.
virtual void ConnectUdp(const string &ip, uint16_t port,
EncodingScheme encoding) = 0;
virtual void ConnectUdp(const boost::asio::ip::tcp::endpoint &endpoint,
EncodingScheme encoding) = 0;

// 현재 버전에선 작동되지 않습니다.
// HTTP 로 서버에 접속합니다. 만약 첫 연결이면 세션이 열리게 됩니다.
virtual void ConnectHttp(const string &url, EncodingScheme encoding) = 0;
virtual void ConnectHttp(const string &ip, uint16_t port,
EncodingScheme encoding) = 0;
virtual void ConnectHttp(const boost::asio::ip::tcp::endpoint &endpoint,
EncodingScheme encoding) = 0;

// 세션 아이디를 반환합니다.
virtual const SessionId &id() const = 0;
// 세션 상태를 반환합니다.
virtual State state() const = 0;

// Transport 의 연결 상태를 확인합니다.
virtual bool IsTransportAttached() const = 0;
virtual bool IsTransportAttached(TransportProtocol protocol) const = 0;

// 서버로 JSON 메시지를 보냅니다.
virtual void SendMessage(const string &message_type, const Json &message,
TransportProtocol protocol) = 0;

virtual void SendMessage(const string &message_type,
const Ptr<FunMessage> &message,
TransportProtocol protocol) = 0;

// Transport 연결을 닫습니다.
// 새로운 트랜스포트가 붙어서 세션을 계속 쓸 수 있기 때문에 세션은 계속 유효한 상태로 남습니다.
virtual void CloseTransport() = 0;
virtual void CloseTransport(TransportProtocol protocol) = 0;

// 세션을 닫습니다.
virtual void Close() = 0;

// 세션 별 Context 를 다루는 인터페이스입니다. 이 컨텍스트는 세션이 살아있는 동안 유효합니다.
// 예)
// boost::mutex::scoped_lock lock(*session); // 필요할 경우 lock 으로 보호
// if (session->GetContext()["my_state"] == ...) {
// ...
// session->GetContext()["my_state"] = ...;
// }
virtual void SetContext(const Json &ctxt) = 0;
virtual Json &GetContext() = 0;
virtual const Json &GetContext() const = 0;
virtual boost::mutex &GetContextMutex() const = 0;
virtual operator boost::mutex &() const = 0;
};

}

static bool Start() {
funtest::Network::Install(OnSessionOpened, OnSessionClosed, 4);

funtest::Network::RegisterTcpTransportHandler(OnTcpAttached, OnTcpDetached);

funtest::Network::Register2("pbuf_echo", OnEcho);

// Created 300 clients.
for (size_t i = 0; i < 300; ++i) {
Ptr<funtest::Session> session = funtest::Session::Create();
session->GetContext()["count"] = 5000;
session->ConnectTcp("127.0.0.1", 8013, kProtobufEncoding);
}

return true;
}


void OnSessionOpened(const Ptr<funtest::Session> &session) {
LOG(INFO) << "[test_client] session created: sid=" << session->id();

string message = RandomGenerator::GenerateAlphanumeric(5, 50);

session->GetContext()["sent_message"] = message;

Ptr<FunMessage> msg(new FunMessage);
PbufEchoMessage *echo_msg = msg->MutableExtension(pbuf_echo);
echo_msg->set_msg(message);
session->SendMessage("pbuf_echo", msg, kTcp);
};


void OnSessionClosed(const Ptr<funtest::Session> &session,
SessionCloseReason reason) {
LOG(INFO) << "[test_client] session closed: sid=" << session->id();
};


void OnTcpAttached(const Ptr<funtest::Session> &session, bool connected) {
if (not connected) {
LOG(ERROR) << "[test_client] failed to connect to the server";
}
};


void OnTcpDetached(const Ptr<funtest::Session> &session) {
LOG(INFO) << "[test_client] tcp transport disconnected: sid=" << session->id
();
};


void OnEcho(const Ptr<funtest::Session> &session, const Ptr<FunMessage> &msg)
{
BOOST_ASSERT(msg->HasExtension(pbuf_echo));

const PbufEchoMessage &echo_msg = msg->GetExtension(pbuf_echo);
const string &message = echo_msg.msg();

string sent_message = session->GetContext()["sent_message"].GetString();
BOOST_ASSERT(sent_message == message);

Json &count_ctxt = session->GetContext()["count"];
count_ctxt.SetInteger(count_ctxt.GetInteger() - 1);
if (count_ctxt.GetInteger() == 0) {
LOG(INFO) << "[test_client] complete: sid=" << session->id();
return;
}

{
string message = RandomGenerator::GenerateAlphanumeric(5, 50);
session->GetContext()["sent_message"] = message;

Ptr<FunMessage> msg(new FunMessage);
PbufEchoMessage *echo_msg = msg->MutableExtension(pbuf_echo);
echo_msg->set_msg(message);
session->SendMessage("pbuf_echo", msg, kTcp);
}
};

}

**Comment by jwlee-ifun** [comment]
안녕하세요.

먼저, 아이펀엔진은 서버로 동작하기 위한 프레임워크이기 때문에 클라이언트로 동작하기 위해서 제공하는 컴포넌트가 `funtest` 입니다.

1. `funtest` 컴포넌트에는 `Session` 클래스를 제공하고 있어서 _Unity_ 나 _Unreal Engine 4_ 플러그인의 `Session` 클래스처럼 사용할 수 있습니다.
2. 아이펀 엔진의 초기화(`***_server.cc` 의 `Install()` 함수)가 끝나고, 시작함수 (`***_server.cc` 파일의 `Start()` 함수) 에서 Session 을 사용해서 요청을 전송하는 클라이언트 동작을 시작하도록 작성합니다.

그리고, 매뉴얼의 [funapi::Network Class](https://www.ifunfactory.com/engine/documents/reference/ko/bot.html#funtest-network) 와 [funapi::Session Class](https://www.ifunfactory.com/engine/documents/reference/ko/bot.html#funtest-session) 설명은 `funtest` 컴포넌트의 기능을 설명하기 위해서 내부 인터페이스 정의를 발췌한 것으로 구현하신 서버 코드에 붙여 넣으실 필요는 없습니다.

실제로 참고하실 만한 부분은 [예제](https://www.ifunfactory.com/engine/documents/reference/ko/bot.html#bot-5000-echo) 이며, `***_server.cc` 파일을 기준으로 설명하고 있습니다. `Start()` 함수는 이미 있으므로 내용을 변경해 주시고, 다른 함수들은 질문자님의 구현에 맞춰서 변경해 주시면 됩니다.

한번 진행해 보시고, 어려운 부분이 있으면 다시 질문 남겨 주시기 바랍니다.
