### ISSUE TITLE
희망 버전 교체 관련

### ISSUE THREAD

**Issue by kimbyoungkyu** [iFunEngine/iFunEngine#239]
Ubuntu 16.04
C++

안녕하세요. 
우분투상에서 다음 명령어를 통해서 엔진을 1.0.0-4738bionic에서 1.0.0-5080xenial로  교체 하고 싶습니다.

sudo apt-get install funapi1-dev=희망버전 funapi1-runtime=희망버전 libfunapi1-mongodblogger=희망버전 python-funapi1-dev=희망버전

1.0.0-5080xenial의 경우 희망버전이 어떻게 되는지요?

참고로 아래 명령어로 시도해봤으나  실패했습니다.

sudo apt-get install funapi1-dev=1.0.0-5080xenial funapi1-runtime=1.0.0-5080xenial libfunapi1-mongodblogger=1.0.0-5080xenial python-funapi1-dev=1.0.0-5080xenial

**Comment by jwlee-ifun** [comment]
안녕하세요.

apt 명령이 실패할 때의 에러 메시지를 올려주시겠어요?

**Comment by kimbyoungkyu** [comment]
root@bob_ch02:~# sudo apt-get install funapi1-dev=1.0.0-5080xenial funapi1-runtime=1.0.0-5080xenial libfunapi1-mongodblogger=1.0.0-5080xenial python-funapi1-dev=1.0.0-5080xenial
패키지 목록을 읽는 중입니다... 완료
의존성 트리를 만드는 중입니다
상태 정보를 읽는 중입니다... 완료
E: funapi1-dev 패키지의 '1.0.0-5080xenial' 버전을 찾을 수 없습니다
E: funapi1-runtime 패키지의 '1.0.0-5080xenial' 버전을 찾을 수 없습니다
E: libfunapi1-mongodblogger 패키지의 '1.0.0-5080xenial' 버전을 찾을 수 없습니다
E: python-funapi1-dev 패키지의 '1.0.0-5080xenial' 버전을 찾을 수 없습니다

**Comment by jwlee-ifun** [comment]
먼저, 사용 중인 Ubuntu 버전 bionic 이시라면 버전에 명시하는 Ubuntu 버전도 (bionic) 이어야 합니다.

`sudo apt-get install funapi1-dev=1.0.0-5080bionic funapi1-runtime=1.0.0-5080bionic libfunapi1-mongodblogger=1.0.0-5080bionic python-funapi1-dev=1.0.0-5080bionic`

**Comment by kimbyoungkyu** [comment]
정정합니다. 엔진 버전 우분투 18.04.3 입니다.

**Comment by jwlee-ifun** [comment]
먼저, 사용 중인 Ubuntu 버전 bionic 이시라면 버전에 명시하는 Ubuntu 버전도 bionic 이어야 합니다.

`sudo apt-get install funapi1-dev=1.0.0-5080bionic funapi1-runtime=1.0.0-5080bionic libfunapi1-mongodblogger=1.0.0-5080bionic python-funapi1-dev=1.0.0-5080bionic`

그리고, root 계정을 사용 중이시라면 sudo 는 제거하셔도 됩니다.
