### ISSUE TITLE
dashboard agent 설치 안되는 문제

### ISSUE THREAD

**Issue by newtrocode** [iFunEngine/iFunEngine#240]
**버전 및 환경 값**
* OS : ubuntu 18.04.3 LTS

**버전 및 환경 값**
* OS : ubuntu 18.04.3 LTS

* 개발 언어 : C# 
  mono : 6.8.0.105

* 개발 환경 : 
  vscode 1.46.10
  c# : 1.22.1
  mono debug : 0.15.8

* 아이펀 엔진 버전: 
  Current repository: experimental
  Current package: fuapi1-runtime_1.0.0-5390bionic: experimental

**어떤 점이 궁금하신가요?**

dashboard 설치를 진행중입니다.

mysql, docker 설치를 마치고

대상 서버에 dashboard agent를 설치하려고 하니

```
$ sudo apt-get install funapi-dashboard-agent

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package funapi-dashboard-agent
```

위와 같이 찾지를 못합니다.

대상 서버에는 ifun engine이 설치되어 있는 상태입니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

먼저, 확인을 부탁드릴 내용이 있습니다. **funapi-dashboard-agent** 는 아이펀 엔진으로 개발하지 않은 서버의 데이터를 수집하기 위한 용도로 사용하며 아이펀 엔진으로 개발한 서버는 **agent** 가 필요하지 않습니다.

만약, 아이펀 엔진으로 개발하지 않은 서버의 데이터를 수집하기 위한 용도가 맞으시다면 다음 내용을 참고 해 주시기 바랍니다.

**funapi-dashboard-agent** 패키지를 찾지 못하는 문제는 아이펀 엔진 저장소가 `stable` 인것 같습니다.

`funapi_select_repo` 명령을 실행하시면 현재 저장소를 확인하실 수 있으며, `stable` 이라면 다음 명령을 실행해서 저장소를 `experimental` 로 변경한 다음 다시 설치해 주시기 바랍니다.

```
sudo funapi_select_repo experimental
sudo apt-get install funapi-dashboard-agent
```

**Comment by newtrocode** [comment]
추후 별도의 서버 정보를 수집하기 위한 용도가 맞습니다.

현재는 기능 확인을 위해 아이펀엔진이 설치된 개발용 머신에 같이 설치를 했습니다.


가이드 주신 부분은 이미 실행을 했었는데 다시 해서 결과를 덫붙입니다.

```
ubuntu@ip-172-30-0-69:~$ sudo funapi_select_repo experimental
Activating iFunEngine experimental repository
Hit:1 http://ap-northeast-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://ap-northeast-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://ap-northeast-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:4 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:5 http://download.mono-project.com/repo/ubuntu stable-bionic/snapshots/6.8 InRelease
Hit:6 https://www.ifunfactory.com/apt bionic InRelease
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Fetched 252 kB in 2s (164 kB/s)
Reading package lists... Done
W: Conflicting distribution: http://download.mono-project.com/repo/ubuntu stable-bionic/snapshots/6.8 InRelease (expected stable-bionic/snapshots/6.8 but got bionic)

ubuntu@ip-172-30-0-69:~$ sudo apt-get install funapi-dashboard-agent
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package funapi-dashboard-agent

ubuntu@ip-172-30-0-69:~$ sudo funapi_select_repo
Current repository: experimental
Current package: fuapi1-runtime_1.0.0-5390bionic: experimental
```

**Comment by jwlee-ifun** [comment]
안녕하세요.

사용하시는 Ubuntu 버전을 착각해서 잘못 안내해 드렸습니다.

**funapi-dashboard-agent** 패키지가 아직 정식 기능으로 배포되지 않은 상태여서 _Ubuntu 16.04 (Xenial)_ 버전만을 지원하고 있습니다.

7월 초 정도에  다른 리눅스 배포판도 지원하도록 서비스를 확장할 예정이오니, 번거로우시더라도 해당 시점에 다시 한번 확인을 부탁드립니다.

ifun-engine-support@ifunfactory.com 으로 메일 주소를 알려주시면, 배포가 되는대로 개별 연락 드리도록 하겠습니다.

안내가 부족해 불편을 드린 점 죄송합니다.

**Comment by newtrocode** [comment]
답변 감사합니다. 추후 배포시에 진행해보겠습니다.
