### ISSUE TITLE
os혼용으로 사용 가능한지요?

### ISSUE THREAD

**Issue by kimbyoungkyu** [iFunEngine/iFunEngine#248]
안녕하세요. 

아이펀 엔진 최신 버전을 기준으로 질문 드립니다.

같은 아이펀 엔진 버전이면 로비,채팅,전투를 담당하는 서버가 극단적으로 각각 "우분투 16.04","센트os 7","윈도우 서버 2016"
라고해도 문제가 없을까요?

약정 걸린 서버중 일부가 "윈도우 서버"라 만약 가능하면하면 혼용해서 사용하고 싶습니다.

**Comment by jwlee-ifun** [comment]
안녕하세요. 아이펀 팩토리입니다.

기본적으로 네트워크를 이용해서 서버들 사이에 통신하기 때문에 문제되는 부분은 없지만, 각 서버 운영체제마다 빌드를 수행해야 하는 번거로움이 있을 수 있습니다.

 Windows 는 물론 우분투와 CentOS 사이에서도 같은 CMake 기반의 리눅스 계열 프로젝트이지만, 빌드 결과물은 거의 호환되지 않으므로 각 운영체제 별로 빌드를 수행해야 합니다.

 또한 Windows 의 경우는 VS 솔루션 형식을 따르기 때문에 각자 프로젝트를 생성하고, src 파일들을 동기화하기 위한 추가 처리가 필요할 것입니다.
