### ISSUE TITLE
[문의]매칭관련

### ISSUE THREAD

**Issue by mkmk8846** [iFunEngine/iFunEngine#249]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_:CentOS 7
* 개발 언어 _(C++/C#)_: C++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: VS
* 아이펀 엔진 버전: ...
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_:Unity
* 클라이언트 플러그인 버전: 2019.3.6f1

**어떤 점이 궁금하신가요?**
안녕하세요 현재 아이펀 엔진 매칭 관련 문의사항이 있습니다.
MatchmakingClient::StartMatchmaking 호출 후 받은 콜백에서 
result 타입 중에 MatchmakingClient::kMRAlreadyRequested 상태가 호출된 경우
매칭 리스트에서 빠지게 되는건가요 
아니면 매칭 리스트에서 빠지지않고 이미 매칭이 호출된 상태라고 메시지만 보내주는건지
궁금합니다.
만약에 매칭에서 빠지게 될경우 다시 MatchmakingClient::StartMatchmaking 함수를 호출하여서
다시 매칭 리스트에 넣어주려고 하고 있습니다.

답변 부탁 드립니다.

**Comment by seonyul2** [comment]
안녕하세요.

매치메이킹 시 중복 요청이 온 경우, 후에 온 요청은 매칭을 진행하지 않고

`MatchResult` 값으로 `MatchmakingClient::kMRAlreadyRequested` 를 보내줍니다.

기존 요청은 매칭리스트에서 빠지지 않고 그대로 처리됩니다.

감사합니다.
