### ISSUE TITLE
[문의]매칭서버관련

### ISSUE THREAD

**Issue by mkmk8846** [iFunEngine/iFunEngine#250]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: CentOS7
* 개발 언어 _(C++/C#)_: c++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: VS
* 아이펀 엔진 버전: ...
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unity
* 클라이언트 플러그인 버전: 2019.3.6f1

**어떤 점이 궁금하신가요?**
_질문 내용을 올려주세요._

안녕하세요 현재 아이펀 엔진 매칭 관련 문의사항이 있습니다
현재 진행 중이 프로젝트에서 점수대 별로 매칭을 시키는 컨텐츠가있는데요
여러개의 매칭 서버를 띄워서 사용할수있는지 문의 드립니다.
예를 들어서 점수가 0~300 대는 A매칭 서버 300~600대는 B매칭 서버 이런식으로
매칭서버를 지정해서 들어갈수있는지 문의 드립니다.

감사합니다.

**Comment by seonyul2** [comment]
안녕하세요.

아래 인터페이스들을 사용하면 매치메이킹 요청 시 `target_server` 를 지정할 수 있습니다.

```
    static void StartMatchmaking(const Type &type, const string &player_id,
        const Json &player_context, const MatchCallback &match_callback,
        const Rpc::PeerId &target_server,
        const ProgressCallback &progress_callback = kNullProgressCallback,
        const WallClock::Duration &timeout = kNullTimeout);
```

또는 

```
    static void StartMatchmaking2(const Type &type, const string &player_id,
        const Json &player_context, const MatchCallback &match_callback,
        const Rpc::PeerId &target_server,
        const ProgressCallback2 &progress_callback = kNullProgressCallback2,
        const WallClock::Duration &timeout = kNullTimeout);
```

먼저, A 매칭 서버와 B 매칭 서버에 각각 태그를 추가해주세요.

`MANIFEST/RpcService` 의 `rpc_tags` 에 직접 추가하시거나

```
"rpc_tags": [ "dungeon_server", "score:200" ]
```

소스 코드에서 AddTag 함수를 통해 추가할 수 있습니다.

```
Rpc::AddTag("score:200");
```
`flavor` 이름은 자동으로 `rpc_tags` 로 사용되니 따로 태그를 추가하지 않고 `flavor` 이름을 사용하셔도 됩니다.

[여기](https://www.ifunfactory.com/engine/documents/reference/ko/distribution.html#distribution-tagging) 에서 자세한 내용을 확인할 수 있습니다.

그리고 매치 메이킹 시작 전 아래 함수로 원하는 조건의 서버의 `PeerId` 를 얻어옵니다.

```
static size_t GetPeersWithTag(Rpc::PeerMap *ret, const Tag &tag, bool include_self=false);
```

다음과 같이 사용합니다.

```
// typedef std::map<PeerId, PeerEndpoint> PeerMap;
Rpc::PeerMap peers;
Rpc::GetPeersWithTag(&peers, "score:200", true);

// 피어 목록 중 적절한 피어를 선택합니다.
// 여기에서는 가장 첫번째 피어를 선택합니다.
Rpc::PeerId peer_id = peers.begin()->first;
```

그리고 위 `StartMatchmaking..` 인터페이스의 `target_server` 변수로 해당 `PeerId` 를 넘겨주시면 됩니다.

단, 이 때 받아오는 피어 목록은 매치메이킹 서버가 아닌 모든 서버를 대상으로 하므로 매치메이킹 서버가 아닌 서버의 `PeerId` 를 넘기지 않도록 주의해 주세요.

매치메이킹서버 목록을 확인하고 싶다면 MatchmakingClient 인터페이스 중 아래 인터페이스를 사용하시면 됩니다.

```
struct MatchmakingServerInfo {
  Rpc::PeerId peer_id;     // 매치메이킹 서버가 동작 중인 피어 ID 입니다.
  size_t player_count;     // 현재 매칭 대기 중인 플레이어 수입니다.
  bool want_more_players;  // 이 서버가 더 많은 사용자를 수용할 수 있는지를
                                           // 결정하는 값입니다.
                                           // player_count 값이 MANIFEST.json 파일 내
                                           // concurrent_number_of_players_threshold 값을
                                           // 넘으면 false, 그렇지 않으면 true 입니다.
};

typedef std::vector<MatchmakingServerInfo> MatchmakingServerInfoVector;

// 매치메이킹 서버 정보를 가져옵니다.
static MatchmakingServerInfoVector GetMatchmakingServerInfo();
```

매치메이킹 서버 목록에 특정 피어가 존재하는지 체크하여 매치메이킹 서버가 맞는지 확인할 수 있습니다.

감사합니다.
