### ISSUE TITLE
AccountManager::SendMessage 링크 관련

### ISSUE THREAD

**Issue by kimbyoungkyu** [iFunEngine/iFunEngine#252]
* OS Windows
* 개발 언어  C++
* 개발 환경 Visual studio 2019
* 아이펀 엔진 버전: 1.0.0-5531 Stable

소스
AccountManager::SendMessage("JoinPvPRoom", MakeResponse(OK), user_id);
AccountManager::SendMessage("PvPMatchingSuccess", respone, user_id);
...

컴파일 결과
error LNK2019: unresolved external symbol "__declspec(dllimport) public: static void __cdecl fun::AccountManager::SendMessageA(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class fun::Json const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum fun::Encryption const &,enum fun::TransportProtocol const &,class boost::function<void __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)> const &)" (__imp_?SendMessageA@AccountManager@fun@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVJson@2@0AEBW4Encryption@2@AEBW4TransportProtocol@2@AEBV?$function@$$A6AXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z@boost@@@Z) referenced in function "void __cdecl matchmaking_server::OnRPCEnterPvPRoom(struct boost::uuids::uuid const &,struct boost::uuids::uuid const &,class boost::shared_ptr<class FunRpcMessage const > const &,class boost::function<void __cdecl(class boost::shared_ptr<class FunRpcMessage> const &)> const &)" (?OnRPCEnterPvPRoom@matchmaking_server@@YAXAEBUuuid@uuids@boost@@0AEBV?$shared_ptr@$$CBVFunRpcMessage@@@4@AEBV?$function@$$A6AXAEBV?$shared_ptr@VFunRpcMessage@@@boost@@@Z@4@@Z)
1>D:\R6\Server2\ifun\x64\Debug\ifun.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "ifun.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

해결 방법이 궁금합니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

올려주신 소스 코드가 위치한 `.cc` 파일이 include  하는 헤더파일 목록을 올려주시겠어요?

**Comment by kimbyoungkyu** [comment]
#pragma once

#include <funapi.h>
#include <gflags/gflags.h>
#include <glog/logging.h>
#include "ifun_loggers.h"
#include "ifun_version.h"
#include "ifun_messages.pb.h"
#include "ifun_object.h"
#include "ifun_rpc_messages.pb.h"
#include "ifun_dedicated_server_rpc_messages.pb.h"
#include "ifun_types.h"
#include "ifun_defines.h"
#include "ifun_data_tables.h"
#include "ifun_msg_parser.h"
#include "ifun_utils.h"

extern "C" {
	#include "ifun_cmdlib.h"
}

**Comment by kimbyoungkyu** [comment]
> 안녕하세요.
> 
> 올려주신 소스 코드가 위치한 `.cc` 파일이 include 하는 헤더파일 목록을 올려주시겠어요?

#pragma once

#include <funapi.h>
#include <gflags/gflags.h>
#include <glog/logging.h>
#include "ifun_loggers.h"
#include "ifun_version.h"
#include "ifun_messages.pb.h"
#include "ifun_object.h"
#include "ifun_rpc_messages.pb.h"
#include "ifun_dedicated_server_rpc_messages.pb.h"
#include "ifun_types.h"
#include "ifun_defines.h"
#include "ifun_data_tables.h"
#include "ifun_msg_parser.h"
#include "ifun_utils.h"

extern "C" {
#include "ifun_cmdlib.h"
}

**Comment by jwlee-ifun** [comment]
Windows 에서 제공하는 SendMessage 정의와 충돌하는 문제가 있는 것을 확인했습니다.

해당 문제를 수정해서 업데이트 하기 전까지 임시로 `Account::SendMessage()` 함수를 사용하는 파일의 머릿부분에 아래 코드를 추가하시면 문제를 우회하실 수 있을 것으로 예상합니다.

```
#include <Windows.h>
#include <WinUser.h>

#undef SendMessage
#define SendMessage SendMessageW
```

**Comment by jwlee-ifun** [comment]
위 문제를 해결한 아이펀 엔진을 배포했습니다.

[링크](https://ifunfactory.com/sub/engine_data_room_windows/stable/1.0.5588.php#builds) 를 통해서 7월 15일 이후에 배포된 버전을 사용해 주시기 바랍니다.

감사합니다.
