### ISSUE TITLE
DB 문의

### ISSUE THREAD

**Issue by claf-yangjh** [iFunEngine/iFunEngine#254]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 18.04)
* 개발 언어 _(C#)
* 개발 환경 _(VS Code)
* 아이펀 엔진 버전: fuapi1-runtime_1.0.0-5571bionic: experimental
* 클라이언트 플랫폼 _(Unity)

**어떤 점이 궁금하신가요?**

1. "activity_log_output"을 여러개 지정 가능한가요?
예를 들면 json / mysql 두 곳으로 저장

2. activity_log_output을 mysql로 지정하는 경우
"db_mysql_server_address"은 ORM으로 사용하고, 별도의 log DB(ORM과는 별개의 mysql) 조회가 가능한가요?
아이펀 서버의 API Service를 사용하여 운영툴을 개발하려고 하는데, 게임서버에서 사용하는 ORM DB와 log DB(ORM과는 별개의 mysql)를 동시에 접속해서 사용하려고 합니다. 가능하다면 설정을 어떻게 하면 될까요?

감사합니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

1. `activity_log_output`설정의 대상은 하나만 가능합니다. 

2. `activity_log_output` 을 MySQL 로 설정하는 포맷은 `mysql://user:passwd@host:port/database` 와 같은데요,
아이펀 엔진에서 제공하는 `mariadb` 객체를 통해서 접근할 수 있습니다. [참고](https://www.ifunfactory.com/engine/documents/reference/ko/db-access-mysql.html)

**Comment by claf-yangjh** [comment]
답변 감사합니다.

2번의 경우
예를 들면 운영툴에서 유저의 레벨을 변경하려면 "db_mysql_server_address"으로 지정한 ORM을 사용하고, 로그 데이터를 조회하기 위해서는 mariadb객체를 따로 사용하면 된다는 의미인거죠?

**Comment by jwlee-ifun** [comment]
네 맞습니다.

만약, 운영툴이 아이펀 엔진이 아니라면 ORM 을 사용할 수 없기 때문에 운영툴 대신 ORM 을 처리할 아이펀 엔진 서버에 RestfulAPI 를 구현해서 운영툴이 호출하도록 하는 방법을 사용하시면 됩니다.

**Comment by claf-yangjh** [comment]
답변 감사합니다.
