### ISSUE TITLE
임의로 LOG 레벨 이름을 추가할 수 있나요?

### ISSUE THREAD

**Issue by swjang-ifunfactory** [iFunEngine/iFunEngine#255]
_고객 문의 내용을 정리해서 옮긴 게시물입니다._

로그를 남기는 파일에 대해 질문 드립니다.

현재 로그를 남길 시. LOG(INFO), LOG(ERROR), LOG(WARNING) 이 세가지를 이용하고 있는데요. 저희가 임의로 LOG(DB_ERROR), LOG(REDIS_ERROR) 이런식으로 사용 할 수 있는지 문의 드립니다.

**Comment by swjang-ifunfactory** [comment]
해당 방식으로 사용하는 건 GLOG 를 전반적으로 직접 확장하지 않으면 어려워 보입니다.

**Comment by jwlee-ifun** [comment]
아이펀 엔진에서 제공하는 로깅 기능은 glog 라이브러리를 사용하고 있기 때문에 glog 에서 지원하지 않는 사용 방식은 사용할 수가 없습니다.

glog 는 Severity level (INFO, WARNING, ERROR, FATAL) 에 따라서 각 파일에 보다 높은 심각도의 로그 내용을 포함해서 기록합니다.

대안으로 로그 타겟 별로 파일을 나누기 위해서 다음 방법 중 하나를 사용할 수 있을 것 같습니다.
1. 로그를 남길 때, Prefix 를 붙이고 로그 파일로부터 해당 Prefix 를 뽑아내는 방식으로 다시 한번 처리.
2. 특정 로그들은 별도 로깅 라이브러리를 사용해서 로그를 남김.
