### ISSUE TITLE
funapi_runner.exe 시작 지점 없음

### ISSUE THREAD

**Issue by kimbyoungkyu** [iFunEngine/iFunEngine#259]
**버전 및 환경 값**
* Windows Server 2016
* C++
* VS 2019
* iFunEngineBundler-VS2019-1.0.5601.exe
* Unreal
* 1.171
 
윈도 서버 2016에서 패키징 설치 이후 배치 파일을 통해서 서버 프로그램을 실행 시키면
다음과 같은 오류가 발생합니다.

![Untitled](https://user-images.githubusercontent.com/51909456/90475534-915c2080-e162-11ea-9071-ca89ac59ac5d.png)

**Comment by SeunghyunNam** [comment]
안녕하세요.

Windows Server 2016 에서 해당 문제가 발생되는 것 확인하였습니다.

이 문제에 대한 수정이 배포되면 이 스레드를 통해 안내드리겠습니다.

감사합니다.

**Comment by kimbyoungkyu** [comment]
윈도우 10에서는 아무 문제 없이 동작하던 버전을 윈도우 서버 2019에서 돌리니 메세지 이벤트가 불규칙하게 블록이 걸렸다 풀리는등 다양한 문제가 발생하더군요. 그래서 혹시나 2016에서 돌려본겁니다. 이왕 확인하시는거 2019년도 점검 해보셔야 할거 같습니다.
수고하세요.

**Comment by jwlee-ifun** [comment]
안녕하세요.

알려주신 문제를 수정한 버전을 [다운로드](https://ifunfactory.com/sub/engine_data_room_windows/experimental/1.0.5610.php#builds) 페이지를 통해서 배포했습니다.

추가로 내부테스트에서 사용하는 프로젝트를 Windows Server 2019 에서 테스트 해보고 있습니다.

아직까지 별다른 문제점을 찾지 못한 상황인데요, 혹시 언급하신 다양한 문제에 대해서 부연 설명 해 주실 수 있으신지요.
