### ISSUE TITLE
ORM 칼럼 변경 및 수정 관련

### ISSUE THREAD

**Issue by mkmk8846** [iFunEngine/iFunEngine#261]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_:CentOS7
* 개발 언어 _(C++/C#)_: c++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: VS
* 아이펀 엔진 버전: ...
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unity
* 클라이언트 플러그인 버전: ...

**어떤 점이 궁금하신가요?**
안녕하세요 아이펀 엔진을 사용하고있는 사용자 입니다.
ORM관련 해서 문의 드릴께 있습니다.

1. ORM 칼럼 이름 변경 관련
  "User": {
    "Id": "String(16) KEY",
    "NickName": "String(16)",
    "Level": "Integer32",
    "Exp": "Integer64",
    "Point": "Integer32",
    "Gold": "Integer64",
    "Gem": "Integer64",
  },

위와 같이 User라는 오브젝트를 정의 했을때
Gem이라는 칼럼을 
"User": {
    "Id": "String(16) KEY",
    "NickName": "String(16)",
    "Level": "Integer32",
    "Exp": "Integer64",
    "Point": "Integer32",
    "Gold": "Integer64",
    "Jewelry": "Integer64",
  },

Jewelry 라는 칼럼으로 이름만 변경하고 기존에 값을 그대로 유지하려고 하는데요
어떤식으로 하면 되는건가요?
칼럼 이름이 Jewelry 라는 칼럼으로 변경 될경우 Gem 칼럼은 사라지는건가요?

2. ORM 칼럼 추가
  "User": {
    "Id": "String(16) KEY",
    "NickName": "String(16)",
    "Level": "Integer32",
    "Exp": "Integer64",
    "Point": "Integer32",
    "Gold": "Integer64",
    "Gem": "Integer64",
  },

위와 같이 User라는 오브젝트를 정의 했을때
개발중에 User 데이터에 새로 "Grade" 라는 칼럼을 추가 하고
기존에 User 데이터에 "Grade" 값을 전부 10으로 디폴트로 셋팅 하고 싶은데
어떤 식으로 구현을 하면 되는건가요?

3. ORM 칼럼 삭제
  "User": {
    "Id": "String(16) KEY",
    "NickName": "String(16)",
    "Level": "Integer32",
    "Exp": "Integer64",
    "Point": "Integer32",
    "Gold": "Integer64",
    "Gem": "Integer64",
  },

위와 같이 User라는 오브젝트를 정의 했을때
개발중에 User 데이터에 "Gem" 칼럼을 삭제 할경우
DB에서 삭제 되는건가요?

답변 부탁 드립니다.

**Comment by swjang-ifunfactory** [comment]
안녕하세요. 항목 별로 답변 드리겠습니다

감사합니다.

> 1. ORM 칼럼 이름 변경 관련
> Gem이라는 칼럼을
> (...중략...)
> Jewelry 라는 칼럼으로 이름만 변경하고 기존에 값을 그대로 유지하려고 하는데요
> 칼럼 이름이 Jewelry 라는 칼럼으로 변경 될경우 Gem 칼럼은 사라지는건가요?

컬럼 이름을 변경하면, 기존 컬럼 데이터는 DB 에서는 그대로 유지되고, 새 컬럼이 생성됩니다. 다만 이전 컬럼은 더 이상 ORM 으로 접근이 불가능해집니다.

올려 주신 예에서는 `Gem` 컬럼은 DB 상 데이터가 유지되지만, 변경 이후 ORM 으로 접근할 수 없습니다. `Jewelry` 컬럼은 신규 생성합니다.

컬럼 이름만 변경하고 기존 값을 유지하고 싶다면:

1. 이름을 변경하시려는 컬럼을 오브젝트 정의 파일에 새롭게 등록하시고
2. ORM 코드로 이전 컬럼을 새 컬럼으로 복사한 코드를 작성하신 후에
3. 서버를 빌드 및 재시작해서,
4. 오브젝트 정의 파일에서 기존 컬럼을 삭제해주세요.

> 2. ORM 칼럼 추가
> 개발중에 User 데이터에 새로 "Grade" 라는 칼럼을 추가 하고
> 기존에 User 데이터에 "Grade" 값을 전부 10으로 디폴트로 셋팅 하고 싶은데

이미 DB 테이블이 생성된 경우라면:

1.  Grade 컬럼을 오브젝트 정의 파일에 추가하고
2. 모든 오브젝트의 Grade 컬럼을 10 으로 설정하도록 ORM 코드를 작성하신 후
3. 이후 새롭게 오브젝트를 생성하는 경우 Grade 컬럼 값을 10으로 설정하시면 됩니다.
 
> 3. ORM 칼럼 삭제
> 개발중에 User 데이터에 "Gem" 칼럼을 삭제 할경우
> DB에서 삭제 되는건가요?

'User 데이터' 가 오브젝트 정의 파일을 말씀하시는 것이라면, DB 에서 컬럼이 삭제되지는 않고, ORM 으로 접근이 불가능해집니다.
