### ISSUE TITLE
Visual Studio 2019 에서 Linux Dump 파일 디버깅 어떻게 하시나요?

### ISSUE THREAD

**Issue by likeblue74** [iFunEngine/iFunEngine#264]
안녕하세요..
dump파일 디버깅 관련해서 궁금하신 점이 있어서 문의 드립니다.

https://devblogs.microsoft.com/cppblog/debug-linux-core-dumps-in-visual-studio/

문서대로 했는데 잘 안되네요..

**Comment by jwlee-ifun** [comment]
안녕하세요.

해당 기능은 Visual Studio 2019 에서 제공하는 기능이기 때문에 문제 해결이 어려울 수 있는 점 미리 양해 부탁드립니다.

먼저, 리모트 머신에서 직접 dump 파일을 열었을 때는 정상적으로 처리가 되셨는지 궁금합니다.

그리고, Visual Studio 2019 에서 디버깅을 수행했을 때, 에러 메시지나 참고할 만한 내용은 없었는지도요.

**Comment by jinukkim** [comment]
아이펀 엔진에서 생성하는 `.dmp` 파일은 coredump 파일이 아니라서 위 방법으로는 디버깅할 수 없습니다.

1. `.dmp` 파일을 해석하려면 [여기에서 설명하는 `funapi_stackwalk`](https://ifunfactory.com/engine/documents/reference/ko/debug.html#dmp) 를 사용해주시면 됩니다.
2. coredump 를 해석하려는 거라면, [.dmp 파일 대신 coredump 를 남기도록 설정하는 작업](https://ifunfactory.com/engine/documents/reference/ko/debug.html#core)이 필요합니다. 변환 후에는 외부 도구라 확답하긴 어려우나, 위 MS 문서 내용대로 진행 가능할 것으로 보입니다.
