### ISSUE TITLE
IfunEngine 으로 Json , Protobuf 를 사용하지 않고 사용자가 정의한 구조체를 서로 전송할수 있을까요.

### ISSUE THREAD

**Issue by doogypoo77** [iFunEngine/iFunEngine#265]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_:  windows
* 개발 언어 _(C++/C#)_: c++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: vs
* 아이펀 엔진 버전: 1.0.87
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: unreal
* 클라이언트 플러그인 버전: 

**어떤 점이 궁금하신가요?**
ifunengin에서 제공하는 json 과 protobuf 프로토콜을 사용하지 않고 자체적으로 정의한 프로토콜을 사용한 tcp 스트림으로 서버로 사용할수 있는 방법이 있을까요. 있다면 샘플코드가 준비 되어 있다면 공유 부탁 드리겠습니다.

**Comment by jinukkim** [comment]
해당 동작 방식은 지원하지 않습니다.
