### ISSUE TITLE
[문의]리더보드 관련

### ISSUE THREAD

**Issue by mkmk8846** [iFunEngine/iFunEngine#266]
**버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: centOS7
* 개발 언어 _(C++/C#)_: c++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: VS
* 아이펀 엔진 버전: funapi1-runtime 1.0.0-5295centos7: stable
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unity
* 클라이언트 플러그인 버전: 

**어떤 문제인가요?**
안녕하세요 현재 
Ifun Engine으로 게임을 개발 하고 있는 중입니다.
리더보드 쪽을 구현 하려고 리더보드를 서버에 설치 하고 
start를 하였더니 아래와 같은 에러 로그가 떴습니다.
확인 부탁 드립니다.

funapi_leaderboard_server.default[71885]: FunapiLeaderboardServer: got an error while opening libfunapi-leaderboard.so: undefined symbol: fun::Object::SetArrayElementDateTime(std::string const&, unsigned long, boost::posix_time::ptime const&)
다음 문제가 있을 수 있습니다:
1. 해당 심볼을 게임 서버 코드에 정의하지 않았을 수 있습니다.
2. 해당 심볼이 서버 코드에 있지않고, 최근에 funapi1-runtime을 업데이트한 경우
   서버를 다시 빌드하면 해결될 수 있습니다..
   문제가 지속된다면 비호환 변경 사항이 있는지 확인해보세요.
만약 버그라고 생각하시면, 아이펀팩토리(funapi-support@ifunfactory.com)로
연락 주세요.

Message from syslogd@localhost at Sep 18 12:06:17 ...
 funapi_leaderboard_server.default[24300]:FunapiLeaderboardServer: got an error while opening libfunapi-leaderboard.so: undefined symbol: fun::Object::SetArrayElementDateTime(std::string const&, unsigned long, boost::posix_time::ptime const&)
 #012다음 문제가 있을 수 있습니다:
 #0121. 해당 심볼을 게임 서버 코드에 정의하지 않았을 수 있습니다.
 #0122. 해당 심볼이 서버 코드에 있지않고, 최근에 funapi1-runtime을 업데이트한 경우
 

**재현 방법**
_재현 방법에 대해서 알려주세요:_
1. ...
2. ...
3. ...
4. 이렇게 하면 문제가 발생함.

**(선택)원래 어떻게 동작했어야 됐나요?**
_필요하다면 원래 어떻게 동작했어야 됐는데 문제가 생긴건지 알려주세요._

**(선택)스크린샷**
_만일 필요하다면 스크린샷을 붙여주세요. (복사-붙여넣기가 가능합니다.)_

**(선택)로그파일 및 MANIFEST 파일**
_만일 필요하다면 아래 `Attach files by ....` 라고 되어있는 부분을 클릭해서 로그 파일이나 MANIFEST.json 파일을 첨부해주세요._
_파일 첨부가 어려우시면 일부분만 복사-붙여넣기를 해주셔도 됩니다. 시작과 끝에 ``` 를 붙여주시면 보다 읽기 쉽게 붙여넣기가 됩니다._

_MANIFEST.json 파일 안에 DB 비밀 번호 등이 그대로 노출될 수 있으니 이 부분은 지워주세요!!_

**Comment by jwlee-ifun** [comment]
funapi-leaderboard 버전도 알려주시겠어요?

**Comment by mkmk8846** [comment]
> funapi-leaderboard 버전도 알려주시겠어요?
funapi-leaderboard 버젼은 어떻게 확인하요?

**Comment by jwlee-ifun** [comment]
`$ rpm -qa | grep funapi` 결과를 올려주시기 바랍니다.

**Comment by mkmk8846** [comment]
결과 공유 드립니다.

감사합니다.

funapi-leaderboard1-1.0.0-4162centos7.x86_64
python-funapi1-devel-1.0.0-5295centos7.x86_64
funapi1-runtime-1.0.0-5295centos7.x86_64
funapi1-devel-1.0.0-5295centos7.x86_64
funapi-yum-setup-0.1.0-111centos7.x86_64

**Comment by jwlee-ifun** [comment]
현재 설치하신 funapi-leaderboard 4162 버전은 funapi1-runtime 5531 버전에 대응하기 때문에 그보다 낮은 현재 버전의 엔진에서 실행이 되지 않는 상태입니다.

리더보드 패키지를 3855 버전으로 낮추시거나, 엔진 패키지를 5531 버전 이상으로 업그레이드 해 주시기 바랍니다.

그전에 libwebsockets23 mariadb-connector-c 패키지도 삭제 해 주시기 바랍니다.

특별히 현재 엔진 버전을 사용하셔야 하는 게 아니라면 모든 패키지를 최신 버전으로 설치 해 주셔도 됩니다.

```
$ sudo yum erase funapi1-devel-1.0.0-5295centos7.x86_64 funapi1-runtime-1.0.0-5295centos7.x86_64 python-funapi1-devel-1.0.0-5295centos7.x86_64 funapi-leaderboard1-1.0.0-4162centos7.x86_64 libwebsockets23 mariadb-connector-c

$ sudo yum install funapi1-devel funapi-leaderboard1
```

**Comment by mkmk8846** [comment]
말씀하신로 새로 다시 다 설치 했거든요 
기존에 있던 패키지 전부 지우고

근데 빌드 시에

1>  /usr/include/funapi/database/mariadb.h:16:20: fatal error: errmsg.h: 그런 파일이나 디렉터리가 없습니다
1>   #include <errmsg.h>

위와 같이 errmsg.h 를 찾을수없다는 에러가 나오고 있습니다.

**Comment by seonyul2** [comment]
안녕하세요.
아이펀 엔진에서 사용하는 mariadb connector 버전이 바뀌면서 mariadb 관련 라이브러리 파일들이 저장되는 위치가 변경되었는데 게임 서버 빌드 디렉터리에 이전 버전의 경로가 남아있어서 컴파일 시 에러가 발생하고 있는 것 같습니다. `{project-name}-build` 디렉터리를 삭제하시고 `{project-name}-source/setup_build_environment` 로 빌드 디렉터리를 다시 생성한 다음 컴파일을 시도해 주시기 바랍니다.
감사합니다.
