### ISSUE TITLE
static bool Uninstall()  관련 질문

### ISSUE THREAD

**Issue by likeblue74** [iFunEngine/iFunEngine#267]
static bool Uninstall()  호출 되는 시점에서의 네트웍 상태와  DB ,Redis,의 연결 상태 그리고 이벤트 스레드 상태가 궁금합니다.
참 그리고 static bool Uninstall()  함수는 어는 스레드에서 호출이 되는지도 궁금합니다.
그럼 즐거운 한주 되세요 .
감사합니다.

**Comment by SeunghyunNam** [comment]
안녕하세요.

Uninstall() 함수는 Install(), Start(), Stop() 함수와 마찬가지로 메인 스레드에서 호출되며,
아이펀엔진의 모든 컴포넌트들이 정지된 후 불립니다.

말씀하신 이벤트 스레드는 멈춘 상태이며, ORM DB 연결, Redis 연결 모두 끊긴 상태입니다.

종료 전 아이펀엔진의 기능을 호출해야한다면 Uninstall() 함수가 아니라 Stop() 함수에서 처리하시면 됩니다.

감사합니다.

**Comment by likeblue74** [comment]
빠른 답변 감사합니다. 
Install(), Start(), Uninstall()이  있는 cc 파일에 Stop 함수가 없는데요. 
static bool Stop() 이런식로 정의하면 될까요?

**Comment by jwlee-ifun** [comment]
> 빠른 답변 감사합니다.
> Install(), Start(), Uninstall()이 있는 cc 파일에 Stop 함수가 없는데요.
> static bool Stop() 이런식로 정의하면 될까요?

네 맞습니다.

``` 
  static bool Start() {
    LOG(INFO) << "Hello, Cplus server is started!";

    /*
     * Now all Built-in Server component is running.
     * You can use other components and execute "Event".
     */
    Timer::ExpireRepeatedly(boost::posix_time::seconds(1),
        cplus::OnTick);
    return true;
  }

  static bool Uninstall() {
    return true;
  }

  // 추가하실 함수
  static bool Stop() {
    return true;
  }
```

**Comment by SeunghyunNam** [comment]
추가로 {project_name}_server.cc 마지막 줄에 REGISTER_COMPONENT 를 수정해주셔야합니다.

Start() 함수만 쓰신다면 REGISTER_STARTABLE_COMPONENT 로 변경하시면 되며,
Start(), Stop() 함수 모두 쓰신다면 REGISTER_STARTABLE_COMPONENT2 로 변경하시면 됩니다.
