### ISSUE TITLE
[문의] 리더보드 내 랭킹 조회 관련

### ISSUE THREAD

**Issue by mkmk8846** [iFunEngine/iFunEngine#268]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: centos7
* 개발 언어 _(C++/C#)_: c++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: VS
* 아이펀 엔진 버전: 5601
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unity
* 클라이언트 플러그인 버전: ...

**어떤 점이 궁금하신가요?**
안녕하세요 현재 리더보드를 사용해서 랭킹 시스템을 구현하고 있는 상태입니다.

내 랭킹 조회사 rank, score 값이 모두 0으로 나오는 문제가 생겨서 문의 드립니다.

아래 코드가 현재 구현 되어있는 코드 입니다.

		LeaderboardQueryRequest my_rank_search_request(
			"score_rank",
			"test",
			id,
			kAllTime,
			LeaderboardRange(LeaderboardRange::kNearby, 0, 0));

		LeaderboardQueryResponse my_rank_search_response;
		if (not GetLeaderboardSync(my_rank_search_request, &my_rank_search_response)) {
			LOG(ERROR) << "leaderboard system error";
			rank_response->set_result(PbufEnumResultMessage::FAIL);

			session->SendMessage(MESSAGE_DEFINE(pbuf_rank_respon se), response, kDefaultEncryption, kTcp);

			return;
		}

id에는 테스트 할 id가 입력 되어있고요
my_rank_search_response 에 records 배열 값을 봤더니 아이디는 정확히 들어있는데 
다른 값들이 전부 0으로 나오고 있습니다(rank, score, percentage 값 보두 0입니다).

확인 부탁드립니다.

감사합니다.

**Comment by SeunghyunNam** [comment]
안녕하세요.

아이펀팩토리입니다.

자기 자신의 랭킹을 조회할 때 입력된 점수가 없을 경우 rank, score, percentage 값이 0 으로 반환됩니다.
혹시 이 경우에 해당하는 것은 아닌지요?

테스트하시는 ID 로 SubmitScoreSync(또는 SubmitScore) 함수를 호출하여 점수를 입력 후에도 같은 현상이 발생하는지 확인 부탁드립니다.

감사합니다.

**Comment by mkmk8846** [comment]
> 안녕하세요.
> 
> 아이펀팩토리입니다.
> 
> 자기 자신의 랭킹을 조회할 때 입력된 점수가 없을 경우 rank, score, percentage 값이 0 으로 반환됩니다.
> 혹시 이 경우에 해당하는 것은 아닌지요?
> 
> 테스트하시는 ID 로 SubmitScoreSync(또는 SubmitScore) 함수를 호출하여 점수를 입력 후에도 같은 현상이 발생하는지 확인 부탁드립니다.
> 
> 감사합니다.

안녕하세요 답변 감사합니다 현재 로그인시 강제적으로

 테스트 아이드를 SubmitScoreSync로 랭킹 정보를 갱신해주고 있습니다 그래도 모든값이 0이 나오고 있습니다 1위 부터 100 위 까지 조회 하는 코드는 데이터가 잘 나오고 있습니다

**Comment by jinukkim** [comment]
`SubmitScore` 함수를 호출 할 때 처음 세 가지 인자가 각각,

- 리더보드 아이디 (일반 랭킹, 래더 랭킹, 같은 임의의 리더보드 이름)
- 유저 아이디의 서비스 프로바이더 부분 (facebook, google-play 같은 임의의 서비스 아이디)
- 유저 아이디의 나머지 부분 (john.doe@example.com 같은 고유 아이디)

에 해당합니다.

이 값을 위에서 사용한 아래 값으로 했는지 재차 확인하시기 바랍니다.

- `"score_rank"`
- `"test"`
- `id` (처음 올린 코드의 id에 해당하는 값)

**Comment by jwlee-ifun** [comment]
안녕하세요.

다음 코드를 올려주시기 바랍니다.

* 스코어를 업데이트하는 ScoreSubmissionRequest 객체를 생성하는 코드.
* 자신의 스코어를 조회하는 LeaderboardQueryRequest 객체를 생성하는 코드.
* LeaderboardQueryResponse 객체로부터 데이터를 뽑아내는 코드.

**Comment by mkmk8846** [comment]
> 안녕하세요.
> 
> 다음 코드를 올려주시기 바랍니다.
> 
> * 스코어를 업데이트하는 ScoreSubmissionRequest 객체를 생성하는 코드.
> * 자신의 스코어를 조회하는 LeaderboardQueryRequest 객체를 생성하는 코드.
> * LeaderboardQueryResponse 객체로부터 데이터를 뽑아내는 코드.

안녕하세요

확인 결과 저희쪽에서 잘못 호출을 하고있었네요 서비스 프로바이더가 잘못 된거 확인하였습니다.

감사합니다
