### ISSUE TITLE
데디케이트 서버 호스트가 할당 포트 이상

### ISSUE THREAD

**Issue by newtrocode** [iFunEngine/iFunEngine#270]
**버전 및 환경 값**
* OS : ubuntu 18.04.4 LTS

* 개발 언어 : C# 
  mono : 6.8.0.123

* 개발 환경 : 
  vscode 1.49.1
  c# : 1.22.1
  mono debug : 0.15.8

* 아이펀 엔진 버전: 
  Current repository: experimental
  Current package: fuapi1-runtime_1.0.0-5571bionic: experimental

**어떤 문제인가요?**

데디케이트 서버 호스트가 데디케이트에 할당 하는 포트가 

7500 ~ 8000번(https://github.com/iFunEngine/iFunEngine/issues/260#issuecomment-685197463)으로 알고 있습니다.

7999번 이후 5000번으로 계속 할당되어 문제가 발생 하고 있습니다.

**재현 방법**

데디케이트를 스폰, 플레이, 종료를 반복 하면 7999번 이후 발생합니다.

**(선택)원래 어떻게 동작했어야 됐나요?**

7500번이나 bind 안되어있는 포트가 전달되어야 할 것 같네요.

**Comment by jwlee-ifun** [comment]
안녕하세요.

말씀하신 내용을 확인했으면 수정해서 배포하고, 이 게시물을 통해서 알려드리도록 하겠습니다.

**Comment by newtrocode** [comment]
네 감사합니다.

**Comment by jwlee-ifun** [comment]
알려주신 내용을 수정한 데디케이티드 서버 호스트 매니저 패키지 (1.0.0-5686 Experimental) 을 배포했습니다.

Stable 버전에 반영되는 것은 11월 정기 배포 시점이 될 예정입니다.

확인 후 문의 사항이 있으시면 알려주시기 바랍니다.

감사합니다.

**Comment by jwlee-ifun** [comment]
아이펀 엔진 1.0.0-5738 Stable 에도 동일한 수정 사항이 반영되었습니다.
