### ISSUE TITLE
[문의]모바일 환경에서 재연결 관련

### ISSUE THREAD

**Issue by mkmk8846** [iFunEngine/iFunEngine#271]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: centos7
* 개발 언어 _(C++/C#)_: c++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: VS
* 아이펀 엔진 버전: 5601
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unity
* 클라이언트 플러그인 버전: ...

**어떤 점이 궁금하신가요?**
_질문 내용을 올려주세요._

안녕하세요 현재 Ifun Engine을 사용하고 있는 사용자 입니다.
Session 재연결 관련 서버 클리아언트 나눠서 질문 드립니다.

클라이언트 질문 :
사용자가 스마트폰을 사용하여 게임을 플레이 중에 홈 버튼을 눌러서 
게임을 잠시 내려 놓고 몇시간후에 다시 돌아올경우
Session의 연결이 끊기지를 판단 하고 끊겼다면 재연결을 시킬려고 합니다.
그리고 서버에서 몇시간 동안 ping이 없을경우 강제로 로그아웃 시킬경우
클라이언트에서 Session연결 후에 현재 로그인  되어있나 체크 해서 로그인이 안되어있다면
로그인도 시켜주려고 합니다.
어떤식으로 Session이 끊겼는지와, 로그인이 되어있는지 체크를 하면 될까요?

서버 질문:
클라이언트에 일정 시간 동안 ping을 보내지 않으면 자동으로 Session을 닫고
로그아웃을 시키고 싶은데요
이설정은 어디서 바꾸면 되는건가요?

감사합니다

수고하세요~

**Comment by seonyul2** [comment]
안녕하세요.

먼저 클라이언트 쪽 문의사항에 대해서 답변 드리겠습니다.

세션의 연결이 끊긴다는 것이 세션이 닫히는 것을 말씀하시는 건가요? 그렇다면 세션이 닫힐 때 서버는 클라이언트로 `session_closed` 메시지를 전송하며 클라이언트에서는 `SessionEvent.kClosed` 이벤트가 발생합니다. `SessionEventCallback` 에서 해당 이벤트가 발생했을 때 Session.Connect() 를 호출하여 재연결해 주시면 됩니다.

클라이언트에서 한 개의 트랜스포트만 사용한 상태에서 핑 타임아웃으로 인해 해당 트랜스포트의 연결이 끊길 경우 `TransportEvent.kStopped`, `SessionEvent.kStopped` 이벤트들만 발생하고 이후 세션 타임아웃으로 인해 세션이 닫혀도 `session_closed` 메시지를 받지 못해  `SessionEvent.kClosed` 이벤트가 발생하지 않는 경우도 있습니다.
이 때, 재연결 후 메시지를 보내면 이미 닫힌 세션으로 메시지를 보낸 것으로 처리되어 서버에서 `session_closed` 메시지를 전송합니다. 그러면 클라이언트에서 `SessionEvent.kClosed` 이벤트가 발생하므로 세션이 닫힌 상황을 처리할 수 있습니다.

사용자가 로그인 되어있는지는 서버의 `AccountManager.CheckAndSetLoggedInAsync` 함수 콜백으로 전달되는 `bool` 값을 통해서 알 수 있습니다. 이미 로그인된 상태라면 `false` 를 전달하며 로그아웃 후 재 로그인 하도록 처리해주시면 됩니다.
`void checkAndSetLoggedInAsync (const string &account_id, const Ptr< Session > &session, const size_t &max_retry, const LoginCallback &login_callback, const LogoutCallback &logout_callback);` 인터페이스를 사용하면 로그인 실패 시 자동으로 로그아웃 후 재 로그인을 시도합니다.

서버 쪽 문의 사항에 대한 답변입니다.

클라이언트에 일정 시간 동안 핑을 보내지 않았을 때 특정 동작을 수행하는 기능은 제공하고 있지 않습니다. 다만 핑 타임아웃이 발생한 경우 해당 트랜스포트의 연결을 끊습니다.

정리하면 현재 연결 구성에 따라 `TransportEvent.kStopped`, `SessionEvent.kStopped`, `SessionEvent.kClosed`  같은 이벤트가 발생했을 때 재연결한 후 서버로 로그인 요청을 보내면 될 것 같습니다.

덧붙여 질문이 있습니다. 핑 타임아웃이 일어난 경우 바로 재연결을 시도하지 않고 세션을 닫으려고 하는 이유를 알 수 있을까요? 참고로 아이펀 엔진은 세션이 닫히면 해당 세션으로 로그인된 사용자는 자동으로 로그아웃 하도록 동작하고 있습니다.

감사합니다.

**Comment by mkmk8846** [comment]
답변 감사합니다
