### ISSUE TITLE
식별자 관련 오류가 발생합니다.

### ISSUE THREAD

**Issue by sharing-hyun** [iFunEngine/iFunEngine#272]
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: Windows
* 개발 언어 _(C++/C#)_: C++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: Visual Studio 2019
* 아이펀 엔진 버전: v1.0.5601

식별자 "project_name"이(가) 정의되어 있지 않습니다.	Ex	C:\Users\User\source\repos\Ex\Ex\src\ex_server.cc	70	
')'가 필요합니다.	Ex	C:\Users\User\source\repos\Ex\Ex\src\ex_server.cc  70	
1>C:\Users\User\source\repos\Ex\Ex\src\ex_server.cc(70,10): error C2065: 'project_name': 선언되지 않은 식별자입니다.
1>C:\Users\User\source\repos\Ex\Ex\src\ex_server.cc(70,27): error C2039: 'OnTick': '`global namespace''의 멤버가 아닙니다.
1>C:\Users\User\source\repos\Ex\Ex\src\ex_server.cc(70,1): error C2146: 구문 오류: ')'이(가) 'OnTick' 식별자 앞에 없습니다.
1>C:\Users\User\source\repos\Ex\Ex\src\ex_server.cc(70,1): error C2146: 구문 오류: ';'이(가) 'OnTick' 식별자 앞에 없습니다.
1>C:\Users\User\source\repos\Ex\Ex\src\ex_server.cc(70,1): error C2059: 구문 오류: ')'
1>C:\Users\User\source\repos\Ex\Ex\src\ex_server.cc(70,1): error C2065: 'OnTick': 선언되지 않은 식별자입니다.

위와같이 식별자 오류가 계속 발생하네요. 설치해야할 파일도 모두 설치하였습니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

프로젝트 생성 과정에서 오류가 발생해서 아이펀 엔진 프로젝트 템플릿의 `project_name` 문자열이 입력한 프로젝트명으로 정상적으로 변환되지 않은 것 같습니다.

몇가지 원인이 있을 수 있어서 프로젝트 생성 당시의 선택 옵션들을 알려주시면 확인에 도움이 될 것 같습니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

Windows 호스트에 설치된 Python 버전이 2.7 인 것 같습니다. CMD 창을 열고, `python --version` 명령의 실행 결과를 확인해 주시기 바랍니다.

아이펀 엔진이 윈도우 환경에서 동작하기 위해서는 Python 3.8 버전이 필요합니다.

만약, 호스트에 두 개 이상의 Python 버전이 설치되어 있는 경우에는 Path 환경 변수를 수정해서 Python 3.8 버전을 사용하도록 설정해 주시기 바랍니다.

위 방법으로 문제가 해결되지 않을 경우 답글 남겨 주시기 바랍니다.

**Comment by jwlee-ifun** [comment]
안녕하세요. 아이펀 팩토리입니다.

오류로 인해 불편을 드려 죄송합니다.

Visual Studio 2019 프로그램 메뉴바의 `확장 -> 확장 관리` 메뉴에서 아이펀 엔진 확장 프로그램을 삭제하시고,

아래 링크에서 다운 받은 확장 프로그램을 설치해서 다시 한번 프로젝트를 생성해 주시기 바랍니다.

https://ifunengine-windows.s3.ap-northeast-2.amazonaws.com/experimental/iFunEngineForWindowsVSIX-1.0.85.vsix
