### ISSUE TITLE
[문의]ORM 삭제 관련 

### ISSUE THREAD

**Issue by mkmk8846** [iFunEngine/iFunEngine#273]
OS (Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows): centos7
개발 언어 (C++/C#): c++
개발 환경 (CMakeLists.txt, VS Code, VS): VS
아이펀 엔진 버전: 5601
클라이언트 플랫폼 (Unity, Unreal, Cocos2d-X, Javascript): Unity
클라이언트 플러그인 버전: ...

**어떤 점이 궁금하신가요?**
안녕하세요 Ifun Engine을 사용 하고있는 사용자입니다.

ORM관련 궁금하게 있어서 문의 드립니다.

현재 임의로 특정 캐릭터를 mysql에서 삭제 하는 로직을 만들고있는데요
Ptr<User> user = User::FetchById(id);
위 코드로 특정 유저를 얻어오고 유저가 있다면
user->Delete(); 를 호출 하였는데요
이렇게 호출하면 MySql 테이블에서도 유저 데이터가 삭제 되는건가요?
아니면 직접 MySql에 접근해서 삭제할 방법이 따로 있는건가요 문의 드립니다.

감사합니다.

**Comment by SeunghyunNam** [comment]
안녕하세요.

아이펀팩토리입니다.

ORM 오브젝트의 ``Delete()`` 함수를 호출하면 MySQL 테이블에서도 삭제됩니다.

만약 삭제하려는 ORM 오브젝트가 다른 ORM 오브젝트를 Attribute 로 포함하고 있다면 이 오브젝트들 또한 함께 삭제됩니다.
(Attribute 가 Foreign 으로 지정된 경우는 함께 삭제되지 않습니다.)

감사합니다.

**Comment by mkmk8846** [comment]
답변 감사합니다.
