### ISSUE TITLE
AccountManager.RedirectClient 호출시 이동될 서버에서 OnClientRedirected 호출이 안됩니다.

### ISSUE THREAD

**Issue by dokyui** [iFunEngine/iFunEngine#274]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: ubuntu 18.04
* 개발 언어 _(C++/C#)_: C#
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: vscode
* 아이펀 엔진 버전: fuapi1-runtime_1.0.0-5677bionic: stable
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unity
* 클라이언트 플러그인 버전: 353

로그 첨부 합니다.
------------------------------------------------------------------------------------------------------------
I1022 04:45:13.079970 29907 transport.cc:495] Client plugin version: 353
I1022 04:45:13.080024 29907 session_message_utils.cc:825] [C->S] TCP/JSON: type=, length=0, session=00000000-0000-0000-0000-000000000000 
[2020-10-22 04:45:13.080] [AS] [DEBUG] TCP Connected: Id(0f8b1b0c-573d-427d-9d54-34834ffd22cf) 
I1022 04:45:13.080354 29907 session_service.cc:3013] A new session is created: sid=0f8b1b0c-573d-427d-9d54-34834ffd22cf, protocol=TCP, encoding=application/json, address=58.230.178.20:56764
I1022 04:45:13.080374 29908 session_message_utils.cc:825] [S->C] TCP/JSON: type=_session_opened, length=94, session=0f8b1b0c-573d-427d-9d54-34834ffd22cf {}
[2020-10-22 04:45:13.080] [AS] [DEBUG] Session Opened: Id(0f8b1b0c-573d-427d-9d54-34834ffd22cf) 
I1022 04:45:13.085494 29906 session_message_utils.cc:825] [C->S] TCP/JSON: type=, length=65, session=0f8b1b0c-573d-427d-9d54-34834ffd22cf 
I1022 04:45:15.294319 29907 session_message_utils.cc:825] [C->S] TCP/JSON: type=session, length=242, session=0f8b1b0c-573d-427d-9d54-34834ffd22cf {"id":"aden66","uid":null,"clientVer":"0.0.3","action":"ClientLogin","name":"ReqClientLogin","responseName":"AckClientLogin","transProtocol":1,"encrypt":100}
I1022 04:45:15.338896 29906 session_message_utils.cc:825] [S->C] TCP/JSON: type=_sc_redirect, length=498, session=0f8b1b0c-573d-427d-9d54-34834ffd22cf {"host":"ec2-52-78-86-242.ap-northeast-2.compute.amazonaws.com","token":"hw+RXwJc65OLxE8fAAAAAAAAAAATAAAAMTYwMjgyODA5NjAwMDUyODAwMTE2MDI4MjgwOTYwMDA1MjgwMDGNIGmQB2c7qtn9q/PA/mMQt0/XdU5JueGAqj1sIiG21g==","flavor":"GS","target_tags":["GS","GS-0.0.3","GS-52.78.86.242"],"current_tags":["AS","AS-0.0.3","AS-52.78.86.242"],"ports":[{"port":8012,"protocol":1,"encoding":1},{"port":8018,"protocol":3,"encoding":1}]}
I1022 04:45:15.342784 29905 session_message_utils.cc:825] [C->S] TCP/JSON: type=, length=65, session=0f8b1b0c-573d-427d-9d54-34834ffd22cf 
I1022 04:45:15.342859 29905 session_message_utils.cc:825] [S->C] TCP/JSON: type=_session_closed, length=105, session=0f8b1b0c-573d-427d-9d54-34834ffd22cf {"_reason":"closed by server"}
I1022 04:45:15.342900 29905 session_service.cc:2195] session closed: sid=0f8b1b0c-573d-427d-9d54-34834ffd22cf, reason=ServerDid
------------------------------------------------------------------------------------------------------------

AS 에서 GS로 이동을 합니다. AS는 8412, 8418, GS는 8012, 8018 포트를 사용하구요, 
서버간 RPC는 연결된거 같은데 RedirectClient를 호출하면 AS에는 성공인데 GS에는 생성된 세션도 없고 콜백도 호출이 안됩니다. 게시판에 관련된 글을보고 다양한 방법으로 시도했는데 안되네요.. 
확인 부탁드립니다.

**Comment by seonyul2** [comment]
안녕하세요.
클라이언트의 로그를 보여주실 수 있을까요?

**Comment by seonyul2** [comment]
안녕하세요.

위 문제는 보통 방화벽이나 공유기 설정 등으로 인해 클라이언트가 이동할 서버로 접속하지 못해 발생하는 경우가 많습니다.
클라이언트에서 GS 로 직접 접속 시도 했을 때 정상적으로 세션이 생성되는지 확인해 보시겠어요?
클라이언트가 직접 접속하는데 문제가 없는데도 서버 이동이 안되는 상황이라면 서버에서 클라이언트로 보내는 서버 이동 정보가 잘못 설정되어있을 가능성이 있습니다.
이런 경우에는 [서버의 IP 주소 알아내기](https://ifunfactory.com/engine/documents/reference/ko/network-subsystem2.html#ip) 내용을 참고하시어 설정을 수정한 후 다시 시도해 주세요.
실제 클라이언트가 전달 받는 서버 이동 정보는 클라이언트의 로그를 통해 확인하실 수 있습니다.

감사합니다.

**Comment by dokyui** [comment]
클라이언트에서 GS로 직접 접속은 가능합니다. ec2-52-78-86-242.ap-northeast-2.compute.amazonaws.com, 52-78-86-242 이렇게 두가지 방식으로 시도했을때 세션 생성은 정상적으로 됩니다. 혹시나 해서 클라쪽 로그를 보니 이상한 부분이 있네요.

-----------------------------------------------------
D[PM 2:25:33] [9272B8] [TCP] [S->C] Json: type=_sc_redirect, length=498 {"host":"ec2-52-78-86-242.ap-northeast-2.compute.amazonaws.com","token":"+RiRXwJc65OLxE8fAAAAAAAAAAATAAAAMTYwMjgyODA5NjAwMDUyODAwMTE2MDI4MjgwOTYwMDA1MjgwMDEyZeHH0qnyLdZigMkkW33vRf5GIx2koaotilIMC1sdEg==","flavor":"GS","target_tags":["GS","GS-0.0.3","GS-52.78.86.242"],"current_tags":["AS","AS-0.0.3","AS-52.78.86.242"],"ports":[{"port":8012,"protocol":1,"encoding":1},{"port":8018,"protocol":3,"encoding":1}],"_sid":"6d884b5d-0abe-4b06-9b60-9edf3fc69688","_msgtype":"_sc_redirect","_seq":1833553111}
I[PM 2:25:33] [536334] [Redirect] host:ec2-52-78-86-242.ap-northeast-2.compute.amazonaws.com, flavor:GS
I[PM 2:25:33] [536334] [Redirect] Current tags [] 
I[PM 2:25:33] [536334] [Redirect] Target tags [] 
W[PM 2:25:33] [536334] onRedirectMessage - Server port list is empty.
W[PM 2:25:33] [9272B8] [TCP] socket closed
D[PM 2:25:33] [9272B8] [TCP] [S->C] Json: type=_session_closed, length=105 {"_reason":"closed by server","_sid":"6d884b5d-0abe-4b06-9b60-9edf3fc69688","_msgtype":"_session_closed"}
-----------------------------------------------------

Server port list is empty. 이런 로그는 정상적인 건가요? 아니면 발생 가능한 경우가 어떻게 될까요?

**Comment by dokyui** [comment]
아..  원인은 찾았습니다. JsonAccessor를 상속받아서 파서를 따로 만들어쓰고있는데 여기서 파싱을 제대로 못하고 있었습니다. 번거롭게 해드려 죄송하네요..

**Comment by seonyul2** [comment]
확인 감사드립니다.
관련하여 이슈가 계속 발생하면 재 오픈 후 다시 질문 부탁드립니다.

감사합니다.
