### ISSUE TITLE
iOS 빌드시 messages.pb.h 빌드에러가 발생합니다.

### ISSUE THREAD

**Issue by RocksquareCjw** [iFunEngine/iFunEngine#277]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: Mac, iOS , Windows
* 개발 언어 _(C++/C#)_: C++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: VS2017 , Xcode12.2
* 아이펀 엔진 버전: 
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unreal 4.25.3
* 클라이언트 플러그인 버전: 1.233

빌드 플랫폼 : Window, Android 
위 환경에서 제공해주시는 ../ThirdParty/proto/build-protobuf-win.bat 파일을 커스텀하여 
messages.pb.h, messages.pb.cc 을 생성했을때는 빌드에러가 발생하지 않지만,

빌드 플랫폼 : iOS 
Windows 환경에서 ../ThirdParty/proto/build-protobuf-win.bat 파일을 커스텀하여
생성한 messages.pb.h, messages.pb.cc 파일이 포함된 프로젝트를 
Mac으로 옮겨 iOS 빌드시에는 에러가 발생합니다.

1.
> messages.pb.h:475:10: error: no viable conversion from returned value of type 'const basic_string<[2 * ...], funapi_allocator<char>>' to function return type 'const basic_string<[2 * ...], allocator<char>>'
ActionThread.ActionDebugOutput:   return ::google::protobuf::internal::NameOfEnum(
ActionThread.ActionDebugOutput:          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ActionThread.ActionDebugOutput: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:799:5: note: candidate constructor not viable: no known conversion from 'const fun::string' (aka 'const basic_string<char, std::char_traits<char>, funapi_allocator<char> >') to 'const std::__1::basic_string<char> &' for 1st argument
ActionThread.ActionDebugOutput:     basic_string(const basic_string& __str);
ActionThread.ActionDebugOutput:     ^
ActionThread.ActionDebugOutput: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:804:5: note: candidate constructor not viable: no known conversion from 'const fun::string' (aka 'const basic_string<char, std::char_traits<char>, funapi_allocator<char> >') to 'std::__1::basic_string<char> &&' for 1st argument
ActionThread.ActionDebugOutput:     basic_string(basic_string&& __str)
ActionThread.ActionDebugOutput:     ^
ActionThread.ActionDebugOutput: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:817:5: note: candidate constructor template not viable: no known conversion from 'const fun::string' (aka 'const basic_string<char, std::char_traits<char>, funapi_allocator<char> >') to 'const char *' for 1st argument
ActionThread.ActionDebugOutput:     basic_string(const _CharT* __s) : __r_(__default_init_tag(), __default_init_tag()) {
ActionThread.ActionDebugOutput:     ^
ActionThread.ActionDebugOutput: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:867:5: note: candidate constructor not viable: no known conversion from 'const fun::string' (aka 'const basic_string<char, std::char_traits<char>, funapi_allocator<char> >') to 'initializer_list<char>' for 1st argument
ActionThread.ActionDebugOutput:     basic_string(initializer_list<_CharT> __il);
ActionThread.ActionDebugOutput:     ^
ActionThread.ActionDebugOutput: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:875:5: note: candidate function
ActionThread.ActionDebugOutput:     operator __self_view() const _NOEXCEPT { return __self_view(data(), size()); }
ActionThread.ActionDebugOutput:     ^

2.

> ActionThread.ActionDebugOutput: /Users/Desktop/iOSBuildBranch/Source/ProjectK1/Network/Protobuf/rsqk_messages.pb.h:500:10: error: no matching function for call to 'ParseNamedEnum'
ActionThread.ActionDebugOutput:   return ::google::protobuf::internal::ParseNamedEnum<PbufCharCreateSC_Result>(
ActionThread.ActionDebugOutput:          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ActionThread.ActionDebugOutput: /Users/Desktop/iOSBuildBranch/Plugins/Funapi/Source/Funapi/Public/google/protobuf/generated_enum_reflection.h:73:6: note: candidate function template not viable: no known conversion from 'const basic_string<[2 * ...], allocator<char>>' to 'const basic_string<[2 * ...], funapi_allocator<char>>' for 2nd argument
ActionThread.ActionDebugOutput: bool ParseNamedEnum(const EnumDescriptor* descriptor,

**Comment by jwlee-ifun** [comment]
별도 채널을 통해서 안내해 드린 바와 같이 위 오류는 UE4.22 버전에 대응하는 아이펀 엔진 플러그인 구버전을 UE4.23 이상 버전에서 사용할 때 발생하는 문제입니다.

해결 방법은
1. 최신 버전의 플러그인을 사용하시거나
2.  protobuf 컴파일 결과물(.pb.cc 또는 .pb.h) 코드에서 다음 컨테이너들의 네임스페이스를 `fun::` 으로 변경해 주시기 바랍니다.

std::ostringstream | fun::ostringstream
-- | --
ostringstream | fun::ostringstream
std::istringstream | fun::istringstream
istringstream | fun::istringstream
std::stringstream | fun::stringstream
stringstream | fun::stringstream
std::string | fun::string
string | fun::string
std::vector | fun::vector
vector | fun::vector
std::queue | fun::queue
queue | fun::queue
std::deque | fun::deque
deque | fun::deque
std::set | fun::set
set | fun::set
std::map | fun::map
map | fun::map
std::unordered_map | fun::unordered_map
unordered_map | fun::unordered_map
