### ISSUE TITLE
ORM Fetch 함수

### ISSUE THREAD

**Issue by dokyui** [iFunEngine/iFunEngine#278]
**(선택)버전 및 환경 값**
* OS : Ubuntu 18.04
* 개발 언어 : C#
* 개발 환경 : VSCode
* 아이펀 엔진 버전: 1.0.0-5677bionic
* 클라이언트 플랫폼 : 
* 클라이언트 플러그인 버전: 

간단히 코드를 예로 들겠습니다.

# object.json
{
"User": {
    "Id": "Integer",
    "Items": "<Integer32, Item> Foreign"
},
"Item": {
    ...
}
}

# code
Event.Invoke(() => {
    var user1 = User.FetchById(1234);
    var user2 = User.FetchById(1234);

    var items1 = user.FetchItems();
    var items2 = user.FetchItems();
});

저렇게 작성하면 안되겠지만.. 예를들어서 하나의 이벤트 안에서 같은 항목에대한 Fetch하면
안되는건지, 만약 된다면 성능상 문제점이 있는건지 궁금합니다.

**Comment by SeunghyunNam** [comment]
안녕하세요.

아이펀팩토리입니다.

한 오브젝트를 반복적으로 Fetch 해도 괜찮습니다.
오브젝트가 캐시에 없었더라도 두 번째 Fetch 부터는 캐시에 올라온 후 캐시에서 읽게 되고,
롤백도 발생하지 않기 때문에 성능 상 큰 문제가 되지는 않습니다.
하지만 가급적 이미 Fetch 해둔 변수를 계속 쓰시는 게 가장 성능이 좋습니다.

감사합니다.

**Comment by dokyui** [comment]
답변 감사합니다. 

한가지 더 궁금한게 fetch된 오브젝트를 클라 요청때마다 fetch 하지않고 전역으로두고 쓰는건 어떤가요?

**Comment by SeunghyunNam** [comment]
Fetch 한 오브젝트는 Fetch 함수를 호출했던 이벤트 함수 내에서만 유효합니다. 이전에 실행된 이벤트에서 Fetch 했던 오브젝트 변수를 다시 사용하려면 Refresh() 함수를 호출해야합니다. 이 함수는 내부적으로 Fetch 처리를 다시 하게 됩니다. 따라서 큰 차이는 없다고 보시면 됩니다.
참고로 전역변수에 넣어두고 Refresh() 를 호출해서 사용할 경우 IsNull() 을 호출해서 삭제 여부를 다시 검사해야합니다.

관련해서 자세한 내용은 아래 링크를 참고 부탁드립니다.

https://www.ifunfactory.com/engine/documents/reference/ko/object3.html#refresh

**Comment by dokyui** [comment]
안녕하세요. ORM 사용중인데 생각과는 달리 동작하는 부분이 있어서요.
A라는 테이블이 있고 id를 key로 설정하고 FetchById로 읽어오는데 테이블에 항목이 있든없든 
처음엔 롤백이되고 두번째에 성공을 하더라구요. 이게 정상동작인지 궁금합니다.
그리고 롤백이되면 해당 이벤트가 재실행되는데 재실행되는 횟수 제한이 있나요?

**Comment by jwlee-ifun** [comment]
안녕하세요.

말씀하신 동작은 정상적인 동작이 맞습니다.

따라서 ORM 오브젝트를 읽어오거나 생성하실 때에는 항상 롤백으로 인해서 로직이 반복 실행 될 수 있음에 유의하지기 바랍니다.

아울러 롤백 횟수에는 제한이 없습니다.

감사합니다.
