### ISSUE TITLE
redis sentinel 사용 방법

### ISSUE THREAD

**Issue by dokyui** [iFunEngine/iFunEngine#279]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: Ubuntu 18.04
* 개발 언어 _(C++/C#)_: C#
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: VS Code
* 아이펀 엔진 버전: 1.0.0-5677bionic
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: ...
* 클라이언트 플러그인 버전: ...

레디스 사용하려고 합니다. Manifest.json에서 enable_redis를 true로 설정하고 sentinel 서버를 사용하는 방법을 알고 싶습니다.  C# 샘플은 찾을수가 없어서요.. 
그리고 RedisClient.Create로 오브젝트를 만들어서 사용중인데 수동으로 sendtinel을 사용 할 수도 있는지 궁금합니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

죄송하지만, 아직 C# 프로젝트에서는 Redis Sentinel 구성을 사용할 수 없습니다.

해당 기능의 구현 가능 여부를 확인한 후에 기능을 배포하면 본 게시물을 통해서 다시 알려드리도록 하겠습니다.

불편을 드려 죄송합니다.

**Comment by dokyui** [comment]
답변 감사합니다. 하나 더 궁금한게 있습니다. 
Mysql ORM은 테이블 정보를 캐시하는걸로 알고있습니다. 캐시된 데이터는 redis에 저장되나요? 그렇다면
redis 서버의 접속 정보는 어디에 세팅을 해야하는지 궁금합니다. enable_redis 옵션을 false로 두고 사용해도 되는지도 궁금하네요.

**Comment by jwlee-ifun** [comment]
ORM 으로 정의되어 서버 런타임에 읽어서 사용한 데이터들을 서버 메모리 상에 `cache_expiration_in_ms` Manifest 설정값 동안  저장합니다.

추가로 Redis 는 서버들 사이에서 ORM 데이터에 대한 소유권을 공유하기 위해서 필요하며, `RpcService` Manifest 설정에서 redis 호스트 정보를 설정해 주시면 됩니다.

**Comment by dokyui** [comment]
빠른 답변 감사합니다.
