### ISSUE TITLE
ORM Event안에서 여러 테이블 fetch

### ISSUE THREAD

**Issue by dokyui** [iFunEngine/iFunEngine#280]
**(선택)버전 및 환경 값**
* OS : Ubuntu 18.04
* 개발 언어 : C#
* 개발 환경 : VSCode
* 아이펀 엔진 버전: 1.0.0-5677bionic
* 클라이언트 플랫폼 : 
* 클라이언트 플러그인 버전: 

# 코드
Event.Invoke(() => {
var a = Account.FetchById(a);
if (a == null)
    a = Account.Create(a);

var b = User.FetchByUid(b);
if (b == null)
    b = User.Create(b);
}

# 질문
계정 테이블에 계정 존재 여부 체크해서 없으면 생성하고 유저테이블에서 유저정보 존재 여부 체크해서 없으면 생성.
이렇게 하나의 이벤트에 두개의 테이블을 읽고 쓰는 작업을하면 User.FetchByUid에서 계속 롤백이 발생하는데
혹시 하나의 이벤트에서 두개의 테이블을 사용하는건 안되는건가요?

**Comment by jwlee-ifun** [comment]
사용할 수 있습니다.

하나의 이벤트 안에서 여러 오브젝트를 읽어오는 경우 오브젝트의 수에 따라서 롤백이 더 많이 발생할 수 있지만,
롤백으로 인해서 이벤트가 실행되지 않는 것은 오류입니다.

만약, `FetchByUid(b)` 의 b 변수가 실행될 때마다 변경되는 경우라면  롤백을 반복할 수 있겠습니다.

**Comment by dokyui** [comment]
User.FetchByUid(b); <= 이부분에서 매번 발생합니다(무한 반복)  

에러메시지 : Exception of type 'funapi.Event+RollbackException' was thrown.
콜스택:
at funapi.EventInternal.Rollback () [0x0001f] in /ramfs/workspace/mono/funapi/event.cs:172 
at funapi.Object.FetchByKey (System.String object_name, System.String attribute_name, System.Object attribute_value, 
  funapi.LockType lock_type) [0x00014] in /ramfs/workspace/mono/funapi/object.cs:67 
at Game.User.FetchByUid (System.Int64 value, funapi.LockType lock_type) [0x00001] in .../mono/ObjectModel/game_object.cs:5050
