### ISSUE TITLE
Rollback exception 없이 Rollback 할수는 없을까요?

### ISSUE THREAD

**Issue by dokyui** [iFunEngine/iFunEngine#281]
**(선택)버전 및 환경 값**
* OS : Ubuntu 18.04
* 개발 언어 : C#
* 개발 환경 : VSCode
* 아이펀 엔진 버전: 1.0.0-5677bionic
* 클라이언트 플랫폼 : 
* 클라이언트 플러그인 버전: 
 
# 질문
fetch된 데이터에 값을 수정한 후 db와 관련없는 이유로 예외처리를 해야할때 수정된 db 데이터를 롤백할 방법은 없을까요?

**Comment by jwlee-ifun** [comment]
안녕하세요.

ORM 오브젝트의 데이터를 변경사항을 되돌리고, 이벤트 실행을 중단하고자 할 때, `Event.Abort()` 함수를 사용하시면 됩니다.

다만, 질문의 의도가 로직 내에서 데이터를 되돌리고, 이어서 다른 코드가 실행되기 원하시는 것이라면 그렇게 동작하지는 않습니다.

abort() 함수를 호출하는 즉시 이벤트는 종료합니다.

**Comment by dokyui** [comment]
답변 감사합니다. 그리고 하나 더..

object_transaction.cc:1705] Assert failed: number_of_keys_created == 0:

이런 에러가 나면서 크래시가 발생하는데 어떤 경우에 발생하는 로그인가요?

복수의 키를가진 테이블에 네개의 row 를 생성하려고하면 발생합니다.

**Comment by jwlee-ifun** [comment]
복합키를 사용하는 오브젝트를 생성할 때 부분적으로 키값이 중복될 때 Assert 가 발생하는 오류를 v1.0.0-5764 Experimental 버전을 통해서 수정했습니다.

Stable 버전에는 2021년 1월 정기 릴리즈에 적용될 예정입니다.
