### ISSUE TITLE
external_ip_resolvers 에 gcloud 옵션 추가 요청

### ISSUE THREAD

**Issue by dokyui** [iFunEngine/iFunEngine#282]
서버간의 이동 처리를 aws에서는 정상적으로 사용 가능했는데
구글클라우드로 넘어오면서 문제가 생기네요. external ip 때문인듯한데
external_ip_resolvers에 gcloud compute engine 추가가 가능할까요?

또한 서버 로딩이후에 HardwareInfo.GetExternalIp() 를 변경할 방법이 있을까요?
private ip를 읽어들였을때 임의로 public으로 변경을 하려고 합니다.

답변 부탁드립니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

질문해 주신 내용을 종합해 봤을 때, external_ip_resolvers 의 nat 키워드를 사용해서 외부에서 바라보는 IP 와 포트를 설정할 수 있습니다.

"external_ip_resolvers": "nat:xxx.xxx.xxx.xxx:tcp+pbuf=8012"
* `xxx.xxx.xxx.xxx` : 특정 호스트를 외부에서 식별하기 위한 공인IP
* `tcp+pbuf:8012` : 특정 호스트의 게임 서비스를 외부에서 식별하기 위한 포트를 설정합니다. 사용하시는 프로토콜과 메시지 인코딩 방식에 따라 tcp+pbuf 또는 tcp+json 와 같은 조합 형태로 포트를 지정하실 수 있습니다.

예를 들어 Public IP 54.65.9.100 의 18012 TCP 포트를 Private IP 192.168.0.100 의 8012 포트(pbuf 사용)로 포워딩하는 환경이라면
"external_ip_resolvers": "nat:54.65.9.100:tcp+pbuf:18012" 와 같이 설정하시면 됩니다.

이 때, GetExternalIp() 함수를 호출하면 54.65.9.100 을 반환합니다.

아울러, HardwareInfo 에 설정된 External IP 를 사용자가 임의로 변경할 수 있는 방법은 없으며, external_ip_resolver 에서 gcloud compute engine 을 지원하는 것도 현재로는 계획에 없지만 향후 개발 계획에 포함해서 검토하도록 하겠습니다.
