### ISSUE TITLE
타이머 정확성 관련~~

### ISSUE THREAD

**Issue by hundrill** [iFunEngine/iFunEngine#283]
안녕하세요..
아이펀엔진 사용을 고려 중 입니다..

개발중인 게임이 타이머가 정확하게 실행이 되어야 되어서 (2-3ms도 오차가 없어야 되어서) 요..

단, 타이머가 tick이 좀 늦게 발생되었으면 다음번에 발생한 tick은 그값을 고려해서 좀 더 빨리 발생 되는 식은 괜찮거든요~ 즉 1초타이머가 정확하게 1초마다 발생되지는 않아도 되지만..그 값이 누적되어서 1시간정도 돌렸을때 차이가 나면 안됩니다..

아이펀엔진의 타이머는 정확하게 오차가 없이 호출이 되고..오차가 있더라도..누적되지 않고..맞춰지는 지요?
그렇지 않다면..타미어 발생 시..Monotonic clock 를 이용하여..지나간 시간을 계산해서 처리 하는식으로 해야 되는지요?

감사합니다~

**Comment by SeunghyunNam** [comment]
안녕하세요.

아이펀팩토리입니다.

타이머는 큰 부하가 없다면 오차가 대체로 1ms 를 초과하지는 않지만, 작은 오차가 누적되어 한 시간 범위로 봤을 땐 차이가 있을 수 있습니다.
이 오차가 게임 개발 시 허용되지 않으신다면 오차가 누적되지 않도록 수정하여 곧 업데이트 하도록 하겠습니다.

감사합니다.

**Comment by hundrill** [comment]
안녕하세요..답변 감사드립니다~
오차가 누적되면 안되는데..생각 해 보니..제가 경과시간을 계산 해서 게임루프를 돌리면 문제가 없을 것 같습니다..감사합니다..
