### ISSUE TITLE
클라이언트 쪽 protobuf 관련 빌드 에러

### ISSUE THREAD

**Issue by hueypark** [iFunEngine/iFunEngine#284]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: Ubuntu 20.04 / Windows
* 개발 언어 _(C++/C#)_: C++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: CMakeLists.txt, VS
* 아이펀 엔진 버전: v1.0.5821
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unreal
* 클라이언트 플러그인 버전: engine-plugin-ue4 V233

**어떤 점이 궁금하신가요?**
안녕하세요.
서버엔진으로 아이펀 엔진을 고려중이며 현재 기본적인 동작을 테스트하고 있습니다.
protobuf 메시지를 추가하기 위해 서버 쪽 프로젝트에서 생성된 `server_messages.pb.h`, `server_messages.pb.cpp` 를 클라이언트로 복사해 빌드 시도하였으나 아래 에러가 발생했습니다.

fatal error C1083: Cannot open include file: 'google/protobuf/port_def.inc': No such file or directory

https://github.com/iFunFactory/engine-plugin-ue4 의 SDK 를 사용하였는데 해당 부분은 직접 수정하여야 하는 것일까요?

해당 내용 확인부탁드립니다.

감사합니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

UE4 는 Protobuf 메시지를 추가한 경우, 클라이언트 개발 환경에서 직접 수정사항을 적용해 주시면 됩니다.

절차는 다음과 같습니다.

1. 서버 쪽에서 사용하는 Protobuf 정의 파일 (.proto) 을 플러그인 디렉터리의 `Plugins/Funapi/ThirdParty/proto` 아래에 복사. (이미 존재하는 test_message.proto 를 덮어쓰고 이름을 변경.)
2. 같은 디렉터리에서 윈도우 개발 환경이라면 `build-protobuf-win.bat` 를 MAC 개발 환경이라면 `build-protobuf-mac.sh` 를 실행.

위 단계를 먼저 진행하시고, UE4 프로젝트를 빌드하시면 됩니다.

**Comment by hueypark** [comment]
확인해주셔서 감사합니다.
좋은 하루 되세요.
