### ISSUE TITLE
기술지원 Slack 초대 관련

### ISSUE THREAD

**Issue by hueypark** [iFunEngine/iFunEngine#285]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: Ubuntu 20.04 / Windows
* 개발 언어 _(C++/C#)_: C++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: CMakeLists.txt, VS
* 아이펀 엔진 버전: v1.0.5821
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unreal
* 클라이언트 플러그인 버전: engine-plugin-ue4 V233

**어떤 점이 궁금하신가요?**
안녕하세요.
서버 엔진으로 아이펀 엔진을 검토중입니다.

현재 시점에서 제가 가장 우려하는 부분은 기능이나 성능보다, 기술지원이 원할하게 이루어질 수 있을까입니다. Slack 메신저를 이용해 채팅을 통한 기술지원이 가능한 것으로 알고 있는데 해당 방에는 어떻게 초대받을 수 있을까요?

**Comment by jinukkim** [comment]
슬랙 기술 지원은 기존 유료 고객(별도 구매 계약)에게 별도 계약을 통한 유료로 제공하고 있습니다.

**Comment by hueypark** [comment]
신규로 계약이 가능할까요? 그리고 비용은 어느정도일까요?
공개된 장소에 기록하기 어렵다면 아래 메일로 상세내용 공유해주시면 감사하겠습니다.
jaewan.huey.park@gmail.com
