### ISSUE TITLE
Register2 의 message_type 파라미터 의미 확인 요청

### ISSUE THREAD

**Issue by hueypark** [iFunEngine/iFunEngine#286]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: Ubuntu 20.04 / Windows
* 개발 언어 _(C++/C#)_: C++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: CMakeLists.txt, VS
* 아이펀 엔진 버전: v1.0.5821
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unreal
* 클라이언트 플러그인 버전: engine-plugin-ue4 V233

**어떤 점이 궁금하신가요?**
아래 Register 함수를 테스트 중입니다.
```cpp
  static void Register2(int32_t message_type,
                        const MessageHandler2 &message_handler);
```
1. 파라미터 중 int32_t message_type 는 어떤 값을 의미하는지 문의드립니다.
2. 관련 문서를 제가 못 찾고 있는 것 같습니다. 혹시 [홈페이지 메뉴얼](https://www.ifunfactory.com/engine/documents/reference/ko/index.html) 외에 위와 같은 내용을 설명한 문서나 코드가 있으면 공유부탁드립니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

매뉴얼의 내용이 이해하기 어렵게 돼 있는 것 같아 사과드립니다.

매뉴얼의 내용을 발췌해서 부연 설명하겠습니다.

가령, 다음과 같은 형태의 메시지를 사용한다고 가정했을 때,

```
// FunMessage 는 아이펀엔진의 Google Protocol Buffers 최상위 메시지입니다.
extend FunMessage {
  optional HelloMessage hello_message = 1000;
  ...
}
message HelloMessage {
  required string user_id = 1;
  required Character character = 2;
}
message Character {
  required string name = 1;
  required int64 level = 2;
}
```

이 때, 메시지 핸들러를 등록하는 방법은 C++ 에서 다음의 세가지 방법을 사용할 수 있습니다.
```
// 가장 일반적인 형태의 사용 방법입니다. HelloMessage 타입 하위 메시지의 이름을 문자열로 사용합니다.
HandlerRegistry::Register2("hello_message", OnHello);

// HelloMessage 타입의 하위 메시지의 optional 인덱스로도 등록 가능합니다.
HandlerRegistry::Register2(1000, OnHello);

// C++에서는 다음과 같이 생성된 메세지 구조체를 메세지 타입으로 지정할 수 있습니다.
// 내부적으로 1000 으로 취급합니다.
HandlerRegistry::Register2(hello_message, OnHello);
```

클라이언트에서 메시지를 보낼 때에서도 메시지 타입을 지정해야 하는데, 첫번째 방식으로 등록한 경우에는 동일하게 "hello_message" 로 지정하고, 두번 째 또는 세번 째 방식으로 등록한 경우에는 1000 과 같이 메시지 타입을 지칭하는 integer 값을 지정해야 합니다.

**Comment by jwlee-ifun** [comment]
아이펀 엔진 매뉴얼 외에 [아이펀 엔진 튜토리얼](https://www.ifunfactory.com/engine/documents/tutorial/ko/index.html) 에서도 기본적인 사용법에 대한 설명을 참고하실 수 있습니다.

**Comment by hueypark** [comment]
답변주셔서 감사합니다.

언리얼 클라이언트의 경우 아래처럼 `set_msgtype2` 에 int 형 값을 설정하면 되는 건가요?
```proto
extend FunMessage {
	optional PbufEchoMessage pbuf_echo = 16;
	optional PbufAnotherMessage pbuf_another = 17;
	optional MsgLoginReq msg_login_req = 18;
	optional MsgLoginRes msg_login_res = 19;
}
```
```cpp
FunMessage msg;
// msg.set_msgtype("msg_login_req");
msg.set_msgtype2(18);
MsgLoginReq* msgLoginReq = msg.MutableExtension(msg_login_req);
msgLoginReq->set_msg("Hello, I am client");

session->SendMessage(msg);
```

**Comment by seonyul2** [comment]
안녕하세요. 답변이 늦어 죄송합니다.
네 맞습니다. 또는 `msg.set_msgtype2(msg_login_req.number())` 와 같이 사용하실 수 있습니다.

**Comment by hueypark** [comment]
@seonyul2 확인해 주셔서 감사합니다.
