### ISSUE TITLE
오브젝트 정의에 관한 질문 입니다.

### ISSUE THREAD

**Issue by taewoo0282** [iFunEngine/iFunEngine#287]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_:  Ubuntu 20.04
* 개발 언어 _(C++/C#)_:  C++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_:  CMakeLists.txt
* 아이펀 엔진 버전: 최신.
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unity
* 클라이언트 플러그인 버전: 최신.

**어떤 점이 궁금하신가요?**
_질문 내용을 올려주세요._

안녕하세요.
아이펀엔진을 사용하여 처음으로 사용해보는 초보입니다.
작업을 하다가 궁금한 점이 생겨서 질문을 드리려 합니다.
object_model에 json 데이터를 생성해두면 빌드? 혹시 실행시에 자동으로 오브젝트 소스 파일등이 생성된다고 매뉴얼에서 보앗습니다만. 
json을 해당 폴더 위치에 두고 빌드와 실행을 해보앗지만 db에 생성된 테이블과 컬럼등은 수정전의 데이터로 보여지고 있습니다.
제가 수정한 것으로 반영이 안되는것 같은데요..
체크해봐야 할 사항이 무엇 있을지요..?

**Comment by jwlee-ifun** [comment]
안녕하세요.

오브젝트 모델을 정의하는 json 파일을 변경하시고, 빌드 및 실행 과정에서 문제가 없었다면 다음 내용을 확인해 보시기 바랍니다.

오브젝트 모델을 변경하는 경우에 따라서 DB 에 반영되는 방식이 다릅니다.

1. 속성을 추가한 경우: DB 스킴에 추가한 속성과 관련한 내용이 반영됨.
2. 속성을 제거한 경우: DB 스킴과 레코드는 유지하고 관련 컬럼은 더이상 사용하지 않음. -> 필요하면 관련 컬럼을 직접 삭제.
3. 속성의 타입이 변경되는 경우: DB 스킴과 레코드가 변경되지 않음. -> DB 스킴과 컴럼 데이터를 수동으로 변경해야 함.

2번, 3번과 같이 동작하는 이유는 엔진이 이미 존재하는 DB 스킴이나 레코드를 변경하는 과정에서 의도하지 않은 데이터의 변경이나 유실이 발생할 수 있기 때문입니다.

만약, 위 내용과 관련이 없는 것으로 보일 경우, 오브젝트를 정의하는 json 파일의 변경 전후 상태를 자세히 알려주시면 추가로 확인해 보겠습니다.

**Comment by taewoo0282** [comment]
답변 감사합니다.

생성되는 json 데이터는 기본 리눅스용 프로젝트를 생성할때 나오는 샘플용으로 생성이 됩니다.
디비 스키마등도 샘플용으로 생성됩니다.

변경한것은

{
  "GameUser": {
    "Uuid": "String(16) KEY",
    "dbid": "String(16) KEY",
    "userNo": "Integer64",
    "appStore": "String(16) KEY",
    "appVersion": "String(16) KEY",
    "deviceModel": "String(16) KEY",
    "deviceCountry": "String(16) KEY",
    "deviceLanguage": "String(16) KEY",
    "osVersion": "String(16) KEY",
    "facebook": "String(16) KEY",
    "google": "String(16) KEY",
    "line": "String(16) KEY",
    "apple": "String(16) KEY",
    "gameCenter": "String(16) KEY",
    "MyCharacter": "Character"
  },
  "Character": {
    "Name": "String(24) KEY",
    "Exp": "Integer",
    "Level": "Integer",
    "Hp": "Integer",
    "Mp": "Integer",
    "str": "Integer"
  }
}

형태로 변경했습니다.

변경후 디비 테이블을 모두 Drop 시키고 서버를 리빌드후에 실행하였음에도 기존의 샘플용 으로 테이블 생성이 되는 현상입니다.

**Comment by taewoo0282** [comment]
답변 감사합니다.

지금 확인해 보니.

프로젝트를 빌드시에 원격 머신에 파일 복사만 되어지고 로컬에서 삭제된 파일은 원격지에 반영이 안되어서 그런 문제가 되는듯합니다.

이것을 해결이 되면 문제 없을듯합니다.

혹시 이런 싱크 문제를 알고 계신지요 ㅠㅜ

**Comment by jwlee-ifun** [comment]
Visual Studio 원격 개발 환경을 사용하시는 것 같은데요, Visual Studio 버전을 알려주시겠어요?

**Comment by taewoo0282** [comment]
Visual Studio 2019 버전 입니다.
삭제된 object_model 애들이 원격지에서는 삭제가 안되는 현상이 있는듯합니다.
Ubuntu 서버에서 소스 폴더 내부를 한번씩 삭제 해가면서 하면 문제 없네요.
