### ISSUE TITLE
worker thread crash 

### ISSUE THREAD

**Issue by dokyui** [iFunEngine/iFunEngine#289]
**버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: Ubuntu 18.04
* 개발 언어 _(C++/C#)_: c#
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: vscode
* 아이펀 엔진 버전: 1.0.0-5821
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: ...
* 클라이언트 플러그인 버전: ...

**어떤 문제인가요?**
간혹 크래시가 발생하는데 코어덤프와  미니덤프도 남지않고 로그 파일에 간략한 정보만 남습니다. 로그 첨부합니다.
재현을 위해 다양한 방법으로 스레드에서 예외를 발생시켜보았지만 아래와같은 로그는 전혀 남지 않습니다.
로그를 통해 동일한 패턴을 찾긴했는데.. 
매 10분마다 google storage에 로그를 업로드합니다. 로그를 보시면 10분마다 slow event 로그가 찍히고 crash가 발생하는
시점이 로그 업로드 시점과 일치합니다.
업로드는  funapi.Timer.ExpireRepeatedly 함수를 이용해 실행하고 handler 함수에 try-catch로 예외를 잡으려고 하지만 내부적으로 발생하는 에러라 잡히지를 않네요.
slow event가 발생한 이후에 매번 crash가 발생하는것도 아닙니다. 부하를 발생시켜도 발생하지않고 오히려 아무도 접속하지않고 업로드할 로그의 사이즈도 아주 작을때인 새벽시간에 종종 발생합니다. (개발 서버이기에 근무 시간이후엔 접속자가 없습니다.)

**재현 방법**
알수가 없습니다.

W0224 10:20:15.989012   336 event_profiler.h:405] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=TimerHandler, event_id=17a33b4c-1230-469f-a870-f60d388f90dc, event_tag=f0971d4b-3f2d-44dd-9096-1e8d24a2b447, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=483, handler_time=0, io_wait_time=0, queue_time=482
W0224 10:20:15.989543   336 event_profiler.h:405] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=TimerHandler, event_id=1ee0c82b-ed07-4445-ba9a-b887d73d5b89, event_tag=f0971d4b-3f2d-44dd-9096-1e8d24a2b447, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=483, handler_time=0, io_wait_time=0, queue_time=483
W0224 10:20:15.990160   336 event_profiler.h:405] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=TimerHandler, event_id=ce75a2c4-6a0d-4d9a-ad96-f6c256bdf9d2, event_tag=f0971d4b-3f2d-44dd-9096-1e8d24a2b447, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=484, handler_time=0, io_wait_time=0, queue_time=483
W0224 10:20:15.990749   336 event_profiler.h:405] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=TimerHandler, event_id=dbc304fe-58c6-4bc6-a654-7f233d82b959, event_tag=f0971d4b-3f2d-44dd-9096-1e8d24a2b447, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=484, handler_time=0, io_wait_time=0, queue_time=484
W0224 10:20:15.991194   336 event_profiler.h:405] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=TimerHandler, event_id=c2ced949-13c8-41e7-adc7-aeaeea7979d6, event_tag=f0971d4b-3f2d-44dd-9096-1e8d24a2b447, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=485, handler_time=0, io_wait_time=0, queue_time=484
W0224 10:20:15.991780   336 event_profiler.h:405] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=TimerHandler, event_id=b24152b1-9fc8-42e1-9df3-d48a1666580f, event_tag=f0971d4b-3f2d-44dd-9096-1e8d24a2b447, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=485, handler_time=0, io_wait_time=0, queue_time=485
W0224 10:20:15.992473   336 event_profiler.h:405] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=TimerHandler, event_id=0ab2235d-d428-4c1b-9e88-56b8edfd7de4, event_tag=f0971d4b-3f2d-44dd-9096-1e8d24a2b447, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=486, handler_time=0, io_wait_time=0, queue_time=485
W0224 10:20:15.993129   336 event_profiler.h:405] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=TimerHandler, event_id=cc781423-1c4e-428f-bfea-a85060546fcf, event_tag=f0971d4b-3f2d-44dd-9096-1e8d24a2b447, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=487, handler_time=0, io_wait_time=0, queue_time=486
I0224 10:21:14.330046   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:22:14.330173   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:23:14.330318   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:24:14.330451   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:25:14.330637   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:26:14.330711   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:27:14.330804   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:28:14.330917   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:29:14.331040   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:30:13.899345   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:31:13.899452   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:32:13.899567   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:33:13.899686   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:34:13.899798   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:35:13.899896   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
W0224 10:35:15.556072   333 event_profiler.h:405] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=TimerHandler, event_id=821668fa-3185-45ff-848c-d6b0fe4381c9, event_tag=f0971d4b-3f2d-44dd-9096-1e8d24a2b447, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=694, handler_time=693, io_wait_time=0, queue_time=0
W0224 10:35:15.556886   333 event_profiler.h:405] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=TimerHandler, event_id=d022d65d-0233-47ce-a545-f6642a9f2bd6, event_tag=f0971d4b-3f2d-44dd-9096-1e8d24a2b447, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=495, handler_time=0, io_wait_time=0, queue_time=495
I0224 10:36:13.900032   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:37:13.900141   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:38:13.900254   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:39:13.762696   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:40:13.762933   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:41:13.762984   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:42:13.763092   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:43:13.763191   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:44:13.763319   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:45:13.763414   312 rpc_service.cc:1391] RPC Status: Running as master, self_id=4201ac12-020b-1720-0000-000000000000, connected=2(0), connecting=0
I0224 10:45:14.777539 26231 fault.cc:343] Caught signal(thread=Threadpool work): 6 (Aborted)
E0224 10:45:14.787448 26231 fault.cc:582] Failed to write the dump to /var/crash/funapi/game.LC/fa76ef5a-37fb-409d-9b6523ad-550b2979.dmp
E0224 10:45:14.791019 26231 main.cc:214] Crashed: Thread=Threadpool work, Event=
E0224 10:45:14.794250 26231 fault.cc:410] Waiting for finalization.
E0224 10:45:14.794459   308 framework.cc:91] System has been crashed. (Thread=Threadpool work, 1.0.0-5821bionic)

**Comment by dokyui** [comment]
참고로 비슷한 패턴으로 세번 발생했습니다. 첫번째 발생시에는 코어덤프 설정이 안되어 있어서 설정을 추가하고 최대한의 방어코드를 넣었지만 계속 크래시가 발생하고 있습니다.
Caught signal(thread=Threadpool work): 6 (Aborted) <-- 이 경우에만 코어덤프가 남지 않습니다. 다른 경우엔 코어덤프가 남는것을 확인하였습니다.

**Comment by jwlee-ifun** [comment]
안녕하세요.

올려주신 로그에서는 명확하게 크래시하는 원인을 알 수 없어서 다음 내용에 대해서 답변을 부탁드립니다.

1. 실제 SIGABRT 의 원인이 되는 Threadpool work 스레드는 아이펀 엔진 외부 스레드 인 것 같아서 이 스레드에서 하는 일이 궁금합니다.
2. 서버가 종료되는 시점에 콘솔에 출력되는 내용이 있을 것으로 예상되는데, 해당 내용이 궁금합니다. 만약, 서비스로 실행하셨다면 `$sudo journalctl -x -u {프로젝트 이름}` 명령으로 확인할 수 있습니다. 메모리나 디스크 또는 File 지시자의 부족으로 어플리케이션이 종되는 상황을 알 수 있습니다.

부가적으로 타이머가 실행하는 함수(이벤트) 내부에서 `Event.SetEventName()` 함수를 사용해서 이벤트 이름을 변경해서 로그 내용을 알기 쉽도록 변경할 수 있습니다.

위 내용을 적용하시어 서버가 크래시하는 상황의 로그 내용을 전달해 주시면 추가 확인을 진행하도록 하겠습니다.
