### ISSUE TITLE
AccountManager::CheckAndSetLoggedInAsync 를 이용한 로그인 함수 호출.

### ISSUE THREAD

**Issue by taewoo0282** [iFunEngine/iFunEngine#290]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_:  Ubuntu 20.04
* 개발 언어 _(C++/C#)_:  C++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_:  CMakeLists.txt
* 아이펀 엔진 버전: 최신.
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Unity
* 클라이언트 플러그인 버전: 최신.

**어떤 점이 궁금하신가요?**
_질문 내용을 올려주세요._

AccountManager::CheckAndSetLoggedInAsync 를 이용하여 로그인 처리를 진행중에 있습니다.

AccountManager 의 로그인 처리가 끝나면. 불리는 방식으로.
AccountManager::CheckAndSetLoggedInAsync(uuid, session, bind(&OnLoggedIn, _1, _2, _3, kJsonEncoding));

OnLoggedIn 가 불러지게 되는데요.

로그를 찍어보니 OnLoggedIn 가 계속 무한 루프처럼 호출되는게 보여지는데요.

무슨 문제일지 궁금합니다.

**Comment by taewoo0282** [comment]
해당 내용을 계속 분석해보니 db 쪽에서 오류나서 그런건지 해당 부분을 주석하니 잘되는데요.
userUuid = UserUuid::Create(uuid, groupNo);
userUuid->SetUserNo(userNo);
user = User::Create(userNo);

이런식으로 Create 를 연속으로 하면 안되는걸가요?

**Comment by taewoo0282** [comment]
한가지 더 궁금한거요.
샤딩 기능을 쓰고있는데요.
userUuid = UserUuid::Create(uuid, groupNo);
userUuid->SetUserNo(userNo);
user = User::Create(userNo);

이렇게 썼을때 
UserUuid::Create 정보와  User::Create 정보가 한 db 에 들어가는건지. 아니면 정보는 샤딩된걸로 그떄 그때 나눠져서 들어가는건지 궁금하네요.

지금 생각에 처음 생성했던  UserUuid::Create 랑 User::Create 랑 동일한 유저다라는건 내부적으로 세션 정보를 가지고 데이터를 같은 샤드 디비에 넣게 되어있는건지. 궁금합니다.

**Comment by seonyul2** [comment]
안녕하세요.

아이펀 엔진은 DB 처리 중 롤백이 일어날 수 있습니다.
로그인 콜백에 롤백을 유발하는 함수(`Create`) 가 있기 때문에 로그인 콜백이 수회 실행될 수 있습니다.
롤백을 발생시키는 함수 이전의 코드는 언제나 재실행될 수 있기 때문에, 롤백을 일으킬 수 있는 함수들을 이벤트 핸들러 가장 앞쪽에 위치시켜야 합니다.
또는 `Event::Invoke` 함수를 사용하여 이벤트를 쪼개는 방법도 있습니다.

자세한 설명은 [여기](https://www.ifunfactory.com/engine/documents/reference/ko/object4.html#object-subsystem-transaction-rollback) 를 참고해 주세요.

**Comment by taewoo0282** [comment]
> 안녕하세요.
> 
> 아이펀 엔진은 DB 처리 중 롤백이 일어날 수 있습니다.
> 로그인 콜백에 롤백을 유발하는 함수(`Create`) 가 있기 때문에 로그인 콜백이 수회 실행될 수 있습니다.
> 롤백을 발생시키는 함수 이전의 코드는 언제나 재실행될 수 있기 때문에, 롤백을 일으킬 수 있는 함수들을 이벤트 핸들러 가장 앞쪽에 위치시켜야 합니다.
> 또는 `Event::Invoke` 함수를 사용하여 이벤트를 쪼개는 방법도 있습니다.
> 
> 자세한 설명은 [여기](https://www.ifunfactory.com/engine/documents/reference/ko/object4.html#object-subsystem-transaction-rollback) 를 참고해 주세요.

한가지 더 궁금한거요.
샤딩 기능을 쓰고있는데요.
userUuid = UserUuid::Create(uuid, groupNo);
userUuid->SetUserNo(userNo);
user = User::Create(userNo);

이렇게 썼을때
UserUuid::Create 정보와 User::Create 정보가 한 db 에 들어가는건지. 아니면 정보는 샤딩된걸로 그떄 그때 나눠져서 들어가는건지 궁금하네요.

지금 생각에 처음 생성했던 UserUuid::Create 랑 User::Create 랑 동일한 유저다라는건 내부적으로 세션 정보를 가지고 데이터를 같은 샤드 디비에 넣게 되어있는건지. 궁금합니다.

**Comment by seonyul2** [comment]
안녕하세요.
샤드는 오브젝트 아이디 (Uuid) 에 따라 나눠지기 때문에 두 오브젝트를 생성할 때 부여받는 오브젝트 아이디에 따라 달라집니다.

**Comment by taewoo0282** [comment]
> 안녕하세요.
> 샤드는 오브젝트 아이디 (Uuid) 에 따라 나눠지기 때문에 두 오브젝트를 생성할 때 부여받는 오브젝트 아이디에 따라 달라집니다.

네 답변 감사합니다.

현재 위에 상황에서 궁금한것이 더 있는데요.

DB 처리중 롤백이 일어날수있다고 하셨는데..

그건 정보가 잘못되었거나 로직적인 부분에서 문제가 될때 롤백이 이루어지는건데요.

지금 제가 작업 하는 상황에서는 오류적인 부분이 보이지 않아서요.

"UserUuid": {
    "Uuid": "String(200) KEY",
    "Group": "Integer64 KEY",
    "UserNo": "Integer64"
  },
  "User": {
    "UserNo": "Integer64 KEY",
    "AppStore": "String(16)",
    "AppVersion": "String(16)",
    "DeviceModel": "String(16)",
    "DeviceCountry": "String(16)",
    "DeviceLanguage": "String(16)",
    "OsVersion": "String(16)",
    "Facebook": "String(16)",
    "Google": "String(16)",
    "Line": "String(16)",
    "Apple": "String(16)",
    "GameCenter": "String(16)"
  }


userUuid = UserUuid::Create(uuid, groupNo);
user = User::Create(userNo);

이런 상황인데요.

혹시  UserUuid::Create 부분에서 커밋이 끝나고 뒤에 Create 가 이루어 져야 하는건지..
로그를 찍어본다면  UserUuid::Create 는 잘 통과 되지만 뒷부분 User::Create(userNo); 에서 롤백이 일어나고있는데.
디비 스키마도 삭제하고 서버에서 자동으로 생성된 상태로 진행을 하는대도 문제가 되는 상황입니다.

**Comment by jwlee-ifun** [comment]
아이펀 엔진에서 오브젝트의 롤백은 오브젝트의 소유권을 관리할 때에도 발생합니다.

즉, `정보가 잘못되었거나 로직적인 부분에서 문제가 될때` 이 외에도 오브젝트를 가져오거나(Fetch), 생성(Create) 하는 등의 상황에서도 발생할 수 있는 점을 인지해 주시면 좋을 것 같습니다.

```
userUuid = UserUuid::Create(uuid, groupNo);
user = User::Create(userNo);
```

위와 같은 구문이 있다고 가정했을 때, 중간에 인위적으로 커밋먼트를 발생시킬 수는 없으며 엔진 내부 로직에 의해서 두 개의 오브젝트를 연달아 생성하는 과정에서 수차례 롤백이 발생할 수 있습니다.

따라서 롤백이 발생할 수 있는 점에 유의하셔서 반복에 의해서 함수 외부에 선언된 변수의 값은 매 실행 때마다 변경될 수도 있는 점 유의해 주시기 바랍니다.

**Comment by taewoo0282** [comment]
> 아이펀 엔진에서 오브젝트의 롤백은 오브젝트의 소유권을 관리할 때에도 발생합니다.
> 
> 즉, `정보가 잘못되었거나 로직적인 부분에서 문제가 될때` 이 외에도 오브젝트를 가져오거나(Fetch), 생성(Create) 하는 등의 상황에서도 발생할 수 있는 점을 인지해 주시면 좋을 것 같습니다.
> 
> ```
> userUuid = UserUuid::Create(uuid, groupNo);
> user = User::Create(userNo);
> ```
> 
> 위와 같은 구문이 있다고 가정했을 때, 중간에 인위적으로 커밋먼트를 발생시킬 수는 없으며 엔진 내부 로직에 의해서 두 개의 오브젝트를 연달아 생성하는 과정에서 수차례 롤백이 발생할 수 있습니다.
> 
> 따라서 롤백이 발생할 수 있는 점에 유의하셔서 반복에 의해서 함수 외부에 선언된 변수의 값은 매 실행 때마다 변경될 수도 있는 점 유의해 주시기 바랍니다.

답변감사합니다.

`엔진내부에서 오브젝트를 두개를 연달아 생성하는 과정에서  수차례 롤백이 발생할수있다.`
라는 것은 안전이 보장 될수없으니 어느 코드에서든 Create 를 연달아서 쓰는것은 안좋다 라는 뜻으로 해석해도 될지요?

**Comment by seonyul2** [comment]
안녕하세요.

Create 를 연달아 실행하지 않더라도 오브젝트의 소유권 관리 상황에 따라 롤백이 일어날 수 있습니다.
롤백을 일으킬 수 있는 코드가 많다면 롤백이 일어나는 횟수가 더 많아질 수 있으므로 `두 개의 오브젝트를 연달아 생성하는 과정에서 수차례 롤백이 발생할 수 있습니다.` 라고 말씀드린 것입니다.

ORM 사용 시 롤백은 항상 발생할 수 있는 현상이기 때문에 롤백이 일어나는 것 자체를 회피할 순 없으며 1.재실행되면 안되는 코드(예를 들어 전역 변수를 증가시키는 코드)가 롤백을 발생시키는 코드의 뒤에 있도록 코드를 배치하거나 2. 롤백을 일으킬만한 코드를 이벤트로 분리하여 롤백에 안전하도록 구현하셔야 합니다.

롤백에 안전한 코드일 경우 Create 를 연달아 쓰는 것이 문제가 되지는 않습니다. 다만 Create 사이에 시간이 오래 걸리는 연산이 있고 롤백으로 인해 수 회 실행될 경우 성능에 영향을 미칠 수는 있습니다.
