### ISSUE TITLE
버전 업데이트 추가된 로그

### ISSUE THREAD

**Issue by aden82** [iFunEngine/iFunEngine#292]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: ubuntu18.04
* 개발 언어 _(C++/C#)_: c#
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: vscode
* 아이펀 엔진 버전: 5833
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: ...
* 클라이언트 플러그인 버전: ...

디버깅하다보면 아래와 같은 로그가 너무 많이 발생하는데 왜이런걸까요?

#로그
W0316 07:34:01.907683 21608 logging.cc:952] /.../game-source/build/logs/glog/funapi_runner.WARNING is not a log file of game_server
W0316 07:34:01.907763 21608 logging.cc:952] /.../game-source/build/logs/glog/funapi_runner.ERROR is not a log file of game_server

**Comment by jwlee-ifun** [comment]
다른 서버 인스턴스의 로그가 한 디렉터리에 남고 있는 경우에 부가적인 로그를 출력하고 있는데,
제거할 예정이므로 무시하셔도 됩니다.

번거로우시겠지만, 업데이트를 기다려주시기 바랍니다.

**Comment by aden82** [comment]
네. 답변 감사합니다.
