### ISSUE TITLE
유니티 버젼 관련

### ISSUE THREAD

**Issue by akstntn** [iFunEngine/iFunEngine#293]
문서에는 유니티 2019까지 지원된다고 써있는데 2020, 2021은 지원이 안되는건가요?

**Comment by seonyul2** [comment]
안녕하세요. 아이펀팩토리 입니다.
유니티 2020 버전에서는 정상적으로 동작합니다.
2021 버전은 확인 후 매뉴얼에 업데이트 하겠습니다.
감사합니다.
