### ISSUE TITLE
Http request 시 발생하는 session id 를 통한 http 유저 관리 예시 문의드립니다.

### ISSUE THREAD

**Issue by hungsikPark** [iFunEngine/iFunEngine#296]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: Ubuntu 18.04
* 개발 언어 _(C++/C#)_: c++
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: vscode
* 아이펀 엔진 버전: fuapi1-runtime_1.0.0-5868bionic: stable

**어떤 점이 궁금하신가요?**
Http request 생성되는 session id 를 쿠키로 저장하여 클라이언트에 전달해 주고 싶습니다.

이후 해당 클라이언트는 Http request 시 해당 session id 로 접속 되게끔 하고 싶습니다.

가능할까요?

**Comment by jwlee-ifun** [comment]
안녕하세요.

만약, HTTP 응답 메시지의 Body 에 기본적으로 포함되는 Session Id 외에 추가로 HTTP 헤더 파라미터로 전달하고 싶으시다면
다음 예처럼 직접 응답 헤더 파라미터를 추가할 수 있습니다.

```
Ptr<HttpClient> client = boost::make_shared<HttpClient>();
client-> SetHeader("Set-Cookie", session->id());
```

다만, `이후 해당 클라이언트는 HTTP Request 시 해당 Session Id 로 접속되게끔 하고 싶다.` 는 질문은 잘 이해하지 못했습니다만,

아이펀 엔진에 접속하는 클라이언트가 같은 Session Id 를 사용할 수 있기 위해서는 다음 조건이 필요합니다.

1. 같은 서버 인스턴스 (IP & Port)에 접속할 것.
2. 클라이언트가 요청 (FunMessage) 에 유효한 Session Id 를 넣어서 보낼 것.

2번에서 유효한.. 이란 다음 요건을 갖춰야 합니다.
* 서버로부터 전달받은
* 서버 쪽에서 닫히지 않은

추가 설명이 필요하다면 피드백 부탁드립니다.

**Comment by hungsikPark** [comment]
답변 감사드립니다.
