### ISSUE TITLE
RpcService 크래시

### ISSUE THREAD

**Issue by aden82** [iFunEngine/iFunEngine#298]
**버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: ubuntu 18.04
* 개발 언어 _(C++/C#)_: c#
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: vscode
* 아이펀 엔진 버전: 1.0.0-6051

Manifest.json/RpcService/rpc_check_connection : true, false 로 변경하면서 테스트
서버를 실행한 후 10~20분후에 크래시 발생 

3. 로그
I0811 03:33:25.963485 28346 manifest_handler.cc:1102] Starting Framework
I0811 03:33:25.963534 28346 manifest_handler.cc:1102] Starting IoService
I0811 03:33:25.963587 28346 manifest_handler.cc:1102] Starting ZookeeperClient
I0811 03:33:25.963603 28346 manifest_handler.cc:1102] Starting RpcService
I0811 03:33:25.963615 28346 rpc_service.cc:1934] Started RPC 025ceb93-8bc4-4f1f-0000-000000000000, 172.31.5.28:8015
I0811 03:33:25.963641 28346 rpc_service.cc:1938] RPC server handshaking completed: peer=025ceb93-8bc4-4f1f-0000-000000000000(self)
I0811 03:33:25.964330 28346 redis_rpc_service.cc:794] Redis RPC backend: shard=1
W0811 03:33:25.967329 28346 redis_rpc_service.cc:2000] Redis shard 0 is ok.
I0811 03:33:25.969491 28346 redis_rpc_service.cc:1190] Trying to issue the RPC cluster ID: 126aa804-62a3-4fe4-9b0f-61cda522934b
I0811 03:33:25.970180 28346 redis_rpc_service.cc:1206] The RPC cluster ID is 126aa804-62a3-4fe4-9b0f-61cda522934b
I0811 03:33:25.970598 28346 redis_rpc_service.cc:1066] The Redis server for RPC backend and this server have different times: 0 seconds
I0811 03:33:25.971144 28398 redis_rpc_service.cc:1371] RPC Connection info published: key=/connections, connection_id=51a959b5-8d38-47b6-a07d-67242413d825
I0811 03:33:25.971997 28346 redis_rpc_service.cc:2578] FlushMyObsoleteObjectsOnInit() started.
I0811 03:33:25.972026 28346 redis_rpc_service.cc:2603] There's no objects that are used in previous process: peer_id=025ceb93-8bc4-4f1f-0000-000000000000
I0811 03:33:25.972443 28398 redis_rpc_service.cc:2137] Run Redis RPC service as master.
I0811 03:33:25.972752 28346 redis_rpc_service.cc:3711] Redis RPC service started: peer_id=025ceb93-8bc4-4f1f-0000-000000000000, connection_id=51a959b5-8d38-47b6-a07d-67242413d825
I0811 03:33:25.972790 28346 manifest_handler.cc:1102] Starting ObjectDirectoryService
I0811 03:33:25.972805 28346 manifest_handler.cc:1102] Starting Object
I0811 03:33:25.973901 28346 manifest_handler.cc:1102] Starting EventDispatcher
I0811 03:33:25.981007 28399 event_queue.cc:355] The event thread has been started.
I0811 03:33:25.981061 28402 event_queue.cc:355] The event thread has been started.
I0811 03:33:25.981086 28401 event_queue.cc:355] The event thread has been started.
I0811 03:33:25.981096 28400 event_queue.cc:355] The event thread has been started.
I0811 03:33:25.981017 28346 manifest_handler.cc:1102] Starting ApiService
I0811 03:33:25.981388 28346 manifest_handler.cc:1102] Starting SessionService
I0811 03:33:25.981549 28346 session_service.cc:972] The server started(TCP with JSON): 0.0.0.0:8012
I0811 03:33:25.981616 28346 session_service.cc:972] The server started(HTTP with JSON): 0.0.0.0:8018
I0811 03:33:25.981648 28346 manifest_handler.cc:1102] Starting Curl
I0811 03:33:25.981842 28346 manifest_handler.cc:1102] Starting HttpClientPool
I0811 03:33:25.981881 28346 manifest_handler.cc:1102] Starting AuthenticationService
I0811 03:33:25.981956 28346 manifest_handler.cc:1102] Starting ClientResourceService
I0811 03:33:25.981976 28346 manifest_handler.cc:1102] Starting AccountManager
I0811 03:33:25.982008 28346 manifest_handler.cc:1102] Starting WorldManager
I0811 03:33:25.982044 28346 manifest_handler.cc:1102] Starting DedicatedServerRpcService
I0811 03:33:25.982066 28346 manifest_handler.cc:1102] Starting GameServer
W0811 03:33:27.224062 28373 (Mono)MysqlDB.cs:232] MysqlTransaction Disposed
W0811 03:33:27.301436 28401 event_profiler.cc:331] Slow event - the event execution time is longer than the warning threshold(since the Event::Post/Invoke() call). Please consider to increase the warning threshold or to improve your event logic.: event_name=Parallel, event_id=797f6194-fe81-4c7e-b51a-9b1b9c37636f, event_tag=dd0c2da8-44bf-47e0-bff2-a11f3c7e1fda, the 'slow_event_log_threshold_in_ms' flag=300, execution_time=711, handler_time=711, io_wait_time=0, queue_time=0
W0811 03:33:38.646324 28373 (Mono)MysqlDB.cs:232] MysqlTransaction Disposed
I0811 03:34:25.972962 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
I0811 03:35:25.972977 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
I0811 03:36:25.972924 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
I0811 03:37:25.972950 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
I0811 03:38:25.973814 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
I0811 03:39:25.972971 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
I0811 03:40:25.972993 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
I0811 03:41:25.973018 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
I0811 03:42:25.972935 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
I0811 03:43:25.972959 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
I0811 03:44:25.972960 28376 rpc_service.cc:1442] RPC Status: Running as master, self_id=025ceb93-8bc4-4f1f-0000-000000000000, connected=0(0), connecting=0
F0811 03:45:07.091157 28398 redis_rpc_service.cc:1389] Failed to update RPC connection, cannot serve anymore. You have to check your Redis keys if they exist: peer_id=025ceb93-8bc4-4f1f-0000-000000000000, connection_id=51a959b5-8d38-47b6-a07d-67242413d825
E0811 03:45:07.093138 28398 main.cc:515] Fatal log information: thread=redis_cb
I0811 03:45:07.093261 28398 fault.cc:343] Caught signal(thread=redis_cb): 6 (Aborted)
E0811 03:45:07.423722 28398 fault.cc:580] Crashdump written to /works/tapcook/TCServer/dev/game-source/build/dumps/d604999c-cd81-4c1b-b7cdc4ad-0b8058fe.dmp
E0811 03:45:07.423883 28398 main.cc:218] Crashed: Thread=redis_cb, Event=
E0811 03:45:07.423962 28398 fault.cc:410] Waiting for finalization.
E0811 03:45:07.424054 28346 framework.cc:90] System has been crashed. (Thread=redis_cb, 1.0.0-6051bionic)
E0811 03:45:07.429639 28346 runtime.cc:865] Stack trace - C#
============================================================
  at System.Environment.get_StackTrace () [0x00000] in <f2b3ab7dfff746f594d2ef5b16ec3c90>:0 
============================================================
E0811 03:45:07.434815 28346 framework.cc:105] Shutdown SessionService.
I0811 03:45:07.444983 28387 socket.cc:520] The TCP socket acceptor was canceled, ignoring the request(error::operation_aborted).
E0811 03:45:07.445020 28388 transport.cc:1349] Failed to set the 'TCP_NODELAY' option, Please check the 'NET_ADMIN' capability key if you're running in Docker: error=system:9
E0811 03:45:07.446449 28346 framework.cc:105] Shutdown EventDispatcher.
E0811 03:45:07.449256 28346 framework.cc:105] Shutdown ObjectLeaser.
E0811 03:45:07.450322 28346 framework.cc:105] Shutdown ObjectTransaction.
E0811 03:45:07.451067 28346 framework.cc:105] Shutdown RpcService.
I0811 03:45:07.455315 28346 redis_rpc_service.cc:3752] FlushMyObsoleteObjectsOnShutdown() skipped.
E0811 03:45:07.456252 28346 framework.cc:105] Shutdown IoService.

**Comment by jwlee-ifun** [comment]
안녕하세요.

위 로그는 Redis 서버에 RPC 멤버 키를 갱신하지 못했을 때 발생합니다.

서버 실행 시 로그 내용 중에 `Started RPC 860a3817-0aa8-7f17-0000-000000000000, 10.10.2.115:6015` 와 같은 내용이 있는데,
여기서 `860a3817-0aa8-7f17-0000-000000000000` 을 peer id 라고 부릅니다.

크래시 전/후로 Redis 서버에 "hgetall /connections" 명령의 결과를 살펴보시면 위의 peer id 를 포함하는 결과를 찾을 수 있는지 확인을 부탁드립니다.

만약, 서버가 동작하는 중에 flushall 같은 명령으로 해당 Key 를 찾을 수 없거나 Redis 서버에 명령을 전송할 수 없으면 문제가 될 수 있습니다.

저희쪽에서 확인해 봤을 때는 시간이 흐르는 것으로는 문제가 발생하는 것으로 파악됩니다.

동일한 문제가 발생할 시 좀 더 자세한 실행 환경을 알려주시면 확인시 참고할 수 있도록 하겠습니다.

감사합니다.

**Comment by aden82** [comment]
해당 문제는 redis 해킹으로 인한 문제였습니다. 
다행히 도커로 실행중이라 해킹이 성공하지는 못했지만 주기적으로 접근해서 백업파일을 만들고 있었네요.

외부에서 접근하는 포트 차단하고 redis에 비번 설정해서 해결했습니다.

혹시 저와같은 문제가 다른분들에게 있으실수도 있으니 링크 남깁니다. (https://www.kurien.net/post/view/33)

확인 감사합니다.

**Comment by jwlee-ifun** [comment]
공유해 주셔서 감사합니다!
