### ISSUE TITLE
Javascript 클라이언트 플러그인 관련하여 질문입니다.

### ISSUE THREAD

**Issue by Uncle-Dobi** [iFunEngine/iFunEngine#304]
**(선택)버전 및 환경 값**
* OS _(Ubuntu 16.04/18.04/20.04, CentOS 7/8, Windows)_: Windows10
* 개발 언어 _(C++/C#)_: html, Javascript
* 개발 환경 _(CMakeLists.txt, VS Code, VS)_: Eclipse
* 아이펀 엔진 버전: ...
* 클라이언트 플랫폼 _(Unity, Unreal, Cocos2d-X, Javascript)_: Javascript
* 클라이언트 플러그인 버전: ...

**어떤 점이 궁금하신가요?**

안녕하세요.
기존 게임이 Unity 클라이언트에서 TCP 프로토콜을 채택하여 iFun 엔진 서버와 메시지 통신을 하고 있는데,
게임에서 처리하던 일부 인터페이스(ex.회원가입)를 웹에서 미리 처리하려고 해서 귀사의 Javascript 클라이언트 메뉴얼을 참조하게 되었습니다.
https://www.ifunfactory.com/engine/documents/reference/ko/client-plugin-js.html#

하지만 플러그인으로 다운받은 ifun-engine-plugin.bundle.js 파일에서 문법 오류가 발생하고 있는데,
혹시 자바스크립트 플러그인에 대해서는 지원이 안되는 것인가요?

![화면 캡처 2021-12-04 185449](https://user-images.githubusercontent.com/92505005/144705299-05291212-6578-447e-8d57-10c7f3aa3059.png)
![화면 캡처 2021-12-04 185506](https://user-images.githubusercontent.com/92505005/144705301-c4559f4d-5dec-4202-bf21-eedaf2a4af94.png)

**Comment by swjang-ifunfactory** [comment]
안녕하세요.

안타깝게도 JavaScript 플러그인은 베타 상태로 기술 지원을 제공하지 않습니다.

불편을 드려 죄송합니다.
